### ISSUE TITLE
Unexpected Javascript injection

### ISSUE THREAD

**Issue by kepler** [zauberzeug/nicegui#1067]
### Description

Hello!

Having a text field, binding its value, and then assigning a JS text to it leads to the execution of that JS.

Here's a MWE (tested in `1.2.21` and `1.1.11`):
```py
from dataclasses import dataclass

from nicegui import ui


@dataclass
class Test:
    text: str = ""


test = Test()

ui.input().bind_value(test, "text")

ui.run()

test.text = "</script><script>alert(document.domain)</script>"
```
which leads to this pop-up and subsequent broken page:
![image](https://github.com/zauberzeug/nicegui/assets/73757/5f074410-b195-46bd-90a7-76d6667cea15)
![image](https://github.com/zauberzeug/nicegui/assets/73757/d63df7f7-9181-4dcc-9e52-dcc2ff06dc7d)

I can surely sanitize inputs manually when assigning, but then the text shown in the input control looks escaped, whereas directly writing JS code into the input field leads to no execution at all.

What is the proper way to allow bound assignment without being potentially exposed to JS injection?

Is it on purpose that it gets executed?

**Comment by falkoschindler** [comment]
Oh wow, thanks for reporting this issue, @kepler!

I just played around with the code and the minimum reproduction basically looks like this:
```py
ui.label('</script>')
```

The string "</script>" is used as innerHTML in the DOM, which closes the script tag, causing all following code to be misinterpreted as HTML. And if you add arbitrary JavaScript code to the string, it is executed.

However, I can't reproduce the alert. You put it after `ui.run()`, which doesn't seem to work since `ui.run()` blocks the execution.

Nevertheless, we need to think about how to deal with possibly malicious label text and input value. For some elements like `ui.html` we already check for `</script>`:
https://github.com/zauberzeug/nicegui/blob/79d9a1a381c16f356ad504f633ebe94044fa5e5d/nicegui/elements/mixins/content_element.py#L80-L81

**Comment by kepler** [comment]
Thanks for looking into that!

I simply ran the script with python and it worked, but you're right, it's not how it would happen in practice. The way this hit me was actually reading from query params and then setting a bound variable. Which is obviously super exposed to malicious use.

**Comment by falkoschindler** [comment]
Oh, ok! The following line is enough to show an alert - but only when running the script for the first time, not via auto-reload:

```py
ui.label('</script><script>alert()</script>')
```

**Comment by firai** [comment]
Is `</script>` the only thing that needs to be prevented? Should all brackets be escaped/encoded in general with [`html.escape`](https://docs.python.org/3/library/html.html#html.escape?) or equivalent?

**Comment by falkoschindler** [comment]
@firai I'm not sure. Last week I experimented a bit with escaping the label text, but couldn't really figure it out.

**Comment by kepler** [comment]
No hopes of fixing this soon?

I'm also not sure how to fix it on my side, as escaping it leads to subpar experience on the text control. I'm considering simply removing `script` tags (but then other closing tags might break the app anyway).

**Comment by falkoschindler** [comment]
@kepler No, there is still hope! 😉

I just spent some time with this problem and came up with PR #1276. It might be a starting point to hopefully fix this issue before the next release.

**Comment by falkoschindler** [comment]
@kepler PR https://github.com/zauberzeug/nicegui/pull/1276 is ready for review. Would you like to have a look and maybe try to break it? 🙂
