### ISSUE TITLE
Implementing Token-by-Token (Streaming) Effect in NiceGUI.

### ISSUE THREAD

**Issue by RiyanParvez** [zauberzeug/nicegui#1128]
### Description

I would like to achieve a token-by-token effect similar to ChatGPT's website using NiceGUI. However, it seems that NiceGUI doesn't currently support a streaming GUI. 

So is there any way through which i can do this?

The chat example just waits for the whole message.

If in side a for loop i change the value of a component, it doesnt update untill the loop ends...

**Comment by falkoschindler** [comment]
HI @RiyanParvez!

If I understand correctly, you're trying to update the UI in small steps while some loop is still running. In principle this is very well possible with NiceGUI:

```py
async def stream():
    for i in range(10):
        l.text += f'{i} '
        await asyncio.sleep(0.2)

ui.button('Stream', on_click=stream)
l = ui.label()
```

It is important to allow the UI to update using an asynchronous `sleep` in this example. If the loop would run synchronously from start to finish, the updates would not be sent to the client, at least not until the function returns.

If you have some long-running process going on (instead of an artificial sleep like above), you should run the computation in an executor. The following example simulates such a computation using the synchronous `time.sleep`. Using `run_in_executor` we can await this computation. Meanwhile the UI gets updated:

```py
def some_heavy_computation(i: int) -> int:
    time.sleep(0.2)  # simulate heavy computation
    return i**2

async def process():
    for i in range(10):
        result = await asyncio.get_event_loop().run_in_executor(None, some_heavy_computation, i)
        l.text += f'{result} '

ui.button('Process', on_click=process)
l = ui.label()
```

**Comment by RiyanParvez** [comment]
Thanks! That worked on the first try!
