### ISSUE TITLE
After using the link component to jump to VSCode, the interface loses response.

### ISSUE THREAD

**Issue by CrystalWindSnake** [zauberzeug/nicegui#1151]
### Description

```python
from nicegui import ui
from inspect import currentframe

cf = currentframe()

ui.button("notify", on_click=lambda: ui.notify("clicked button!!"))
ui.link("back to vscode", f"vscode://file/{__file__}:{cf.f_lineno}")

ui.run()
```

When I click the link on the page to 'back to VSCode' and choose Yes to jump to VSCode, there is no response when I click the button again on the interface.

**Comment by falkoschindler** [comment]
Hi @CrystalWindSnake,
Thanks for reporting this issue!
I guess this is partly caused by how the Browser opens the "vscode://" location. Since the link is opened in the current tab (even though it switches to VS Code), the connection to the NiceGUI server is lost. You can avoid it setting `new_tab=True`:

```py
ui.link("back to vscode", f"vscode://file/{__file__}:{cf.f_lineno}", new_tab=True)
```

I'm not sure if there's anything we can do in NiceGUI to improve the default behavior.

**Comment by CrystalWindSnake** [comment]
Thank you for your prompt response. I will try the method you provided.
