### ISSUE TITLE
run on macos report socket.gaierror: [Errno 8] nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by tianqiqiu** [zauberzeug/nicegui#1178]
### Description

when i run examples on macos, it fails, report socket.gaierror: [Errno 8] nodename nor servname provided, or not known. i use version is 1.3.3

**Comment by rodja** [comment]
Strange. We mostly develop on MacOS and have not encountered this error. Could you try another port like suggested in https://github.com/zauberzeug/nicegui/issues/1154?

**Comment by tianqiqiu** [comment]
i try change port ui.run(port=5500) or ui.run(port=9900) or ui.run(port=8989) . It still report socket.gaierror: [Errno 8] nodename nor servname provided, or not known.  the error is in  File "/Users/tim/Documents/prjall/venv/nicepd/lib/python3.11/site-packages/nicegui/welcome.py", line 16, in get_all_ips
    return [info[4][0] for info in socket.getaddrinfo(socket.gethostname(), None) if len(info[4]) == 2]
i test socket.gethostname() the result is 'ddim.local', ddim is my username. socket.getaddrinfo(socket.gethostname(), None) is report error. my python verison is 3.11.4.

**Comment by tianqiqiu** [comment]
my macos version is 13.4.1(c)

**Comment by rodja** [comment]
Ah your error output probably helped. You can simply fix the issue with `python -m pip install netifaces`. NiceGUI automatically uses it when available because it is more reliable (#1137). Unfortunately `netifaces` requires compilation on all platforms and therefore is optional (#1166).
But in the default installation it should definitely not crash. Could you provide the output if you run

```py
import socket
socket.getaddrinfo(socket.gethostname(), None)
```

In an interactive Python shell?

**Comment by tianqiqiu** [comment]
i installed  netifaces use python -m pip install netifaces. 
run 
```
import socket
socket.getaddrinfo(socket.gethostname(), Non
```e)
 the error still is  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

**Comment by tianqiqiu** [comment]
if add '127.0.0.1  <hostname>' in /etc/hosts, 
```
import socket
socket.getaddrinfo(socket.gethostname(), None)
```
it run correctly

**Comment by Devil-Ryu** [comment]
I had the same proble as you
you can specify host in program like this
```
ui.run(host='127.0.0.1')
```

**Comment by tianqiqiu** [comment]
> I had the same proble as you you can specify host in program like this
> 
> ```
> ui.run(host='127.0.0.1')
> ```

Thank you.

**Comment by pythoninthegrass** [comment]
Thanks for the workaround @Devil-Ryu!

Hardcoding the host IP as loopback works but is inconvenient.

Guessing the [error handling](https://github.com/zauberzeug/nicegui/blob/main/nicegui/run.py#L137) is off somehow. If it's OS-specific, I've used `platform` in the past to some success. Patching `run.py` to catch the OS appears to work with minimal refactoring:

```python
import platform
if platform.system() == 'Darwin':
    host = host or '127.0.0.1'
elif platform.system() == 'Linux':
    host = host or '127.0.0.1'
elif platform.system() == 'Windows':
    host = host or '127.0.0.1'
else:
    host = host or '0.0.0.0'

if fullscreen:
    native = True
if frameless:
    native = True
if window_size:
    native = True
if native:
    show = False
    # host = host or '127.0.0.1'
    port = native_mode.find_open_port()
    width, height = window_size or (800, 600)
    native_mode.activate(host, port, title, width, height, fullscreen, frameless)
# else:
#     host = host or '0.0.0.0'
```
 
Could have implications for running in a docker container (`0.0.0.0`), but otherwise negates having to hardcode the IP address as a keyword arg on macOS.

 ## System Info
**macOS** 12.6.7 (21G651)
**python** 3.11.4

**Comment by rodja** [comment]
Using only `127.0.0.1` as default is not optimal because it will only allow local access and not open on all network interfaces. I would like to see a better fix but I'm not sure I've understand the root-cause of the `socket.gaierror` yet ...

**Comment by pythoninthegrass** [comment]
> Using only 127.0.0.1 as default is not optimal because it will only allow local access and not open on all network interfaces.

That's what it already is. Only difference is now there's a platform check to make sure it's enforced. The `if native` conditional never hits otherwise which leaves a blank `host` variable and/or tries to set `0.0.0.0` which doesn't cooperate with the browser on macOS in my experience. `0.0.0.0` is crucial in Docker for the reason you listed though.

> It seems like this known macos issue

I can ping my localhost just fine. Enabling file sharing to get a website working is not a tenable solution.

Looks like editing `/etc/hosts` to explicitly use the hostname vs. `localhost` is a workaround. Just not ideal from a DX perspective.

```
127.0.0.1       localhost
127.0.0.1       mbp
255.255.255.255 broadcasthost
::1             localhost
```

**Comment by pythoninthegrass** [comment]
> ```python
> import socket
> socket.getaddrinfo(socket.gethostname(), None)
> ```
> 
> in an interactive Python shell?

FWIW hardcoding the hostname in `/etc/hosts` gets different results here:

```python
# 127.0.0.1       mbp
[(<AddressFamily.AF_INET: 2>,
  <SocketKind.SOCK_DGRAM: 2>,
  17,
  '',
  ('127.0.0.1', 0)),
 (<AddressFamily.AF_INET: 2>,
  <SocketKind.SOCK_STREAM: 1>,
  6,
  '',
  ('127.0.0.1', 0))]

# 127.0.0.1       localhost
gaierror                                  Traceback (most recent call last)
Cell In [2], line 1
----> 1 socket.getaddrinfo(socket.gethostname(), None)

File ~/.asdf/installs/python/3.11.4/lib/python3.11/socket.py:962, in getaddrinfo(host, port, family, type, proto, flags)
    959 # We override this function since we want to translate the numeric family
    960 # and socket type values to enum constants.
    961 addrlist = []
--> 962 for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    963     af, socktype, proto, canonname, sa = res
    964     addrlist.append((_intenum_converter(af, AddressFamily),
    965                      _intenum_converter(socktype, SocketKind),
    966                      proto, canonname, sa))

gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by rodja** [comment]
Ah by deactivating all sharing features in the macOS settings, restarting the laptop and deinstalling netifaces I can reproduce the original `socket.getaddrinfo` issue.

**Comment by SK3620** [comment]
I've had the same problem, but using SmartProxy made it work.
