### ISSUE TITLE
https://nicegui.io/ Automatically refresh without reason (with Safari)

### ISSUE THREAD

**Issue by txhy2018** [zauberzeug/nicegui#1211]
### Description

When I visit the website to view documents for learning, the page automatically refreshes without any reason, resulting in a poor experience. I hope the author can investigate this phenomenon. Thank you

**Comment by rodja** [comment]
Thanks for reporting this. We have seen this before and are investigating possible solutions. We will update any progress here!

**Comment by rodja** [comment]
Quite tricky! After long investigations and multiple ping-pong with the fly.io support I can summarize:

1. NiceGUI serves the initial website which then needs to connect back to the server with socket.io to keep browser and backend in sync.
2. https://nicegui.io runs multiple instances around the globe for minimum latency and spawns new instances in each region according to traffic.
3. As long as there is only one server per region, the socket.io websocket connection is routed back to the right instance which has served the website.
4. In the last few weeks we have experienced more and more traffic; most of the time spiking in one or two regions.
5. This resulted in additional instances where demand is high -- and reduced the chance that socket.io connects back to the correct instance, resulting in page reloads until the user get's lucky.

To fix this we need to route the socket.io connection back to the original instance which served the page. fly.io provides a `fly-force-instance-id` header. Unfortunately web browsers do not allow to set custom headers for websocket connections. Therefore the fix in #1262 changes the socket.io transport from websocket to long polling. Not ideal but I have no other solution right now.

I spend quite some time to evaluate Google Cloud Run as an alternative to fly.io because they have cookie-based session affinity. But I have not been able to reduce the initial resposnse time below 1.5 seconds yet.

**Comment by rodja** [comment]
> @rodja Could #1212 be related?

Yes. I hope so. I'll try once we have released the fix #1262 into production.

**Comment by pythonormen** [comment]
Hope you will find a solution for this as it must be such an unnecessary negative first impression for new users.

Also will it improve the user experience on mobile?
Nicegui site is so slugish on mobile.

**Comment by rodja** [comment]
@pythonormen is it still happening for you? We have released a fix a few days ago and could not reproduce the error anymore.

**Comment by Xtreemrus** [comment]
Hello, for page https://nicegui.io/documentation/tree#expand_programmatically still auto refresh again and again.
Safari 16.1 (18614.2.9.1.12)

**Comment by rodja** [comment]
You are right. On Chrome all looks good. But on Safari it is inacceptable:
![Jul-29-2023 15-38-14](https://github.com/zauberzeug/nicegui/assets/131391/e476bd7e-6f7c-40d1-ab69-2788a89315b9)

**Comment by rodja** [comment]
I think I found a solution in the minimal example https://github.com/zauberzeug/fly_fastapi_socketio. It seems that it is indeed possible to inject headers into the response of an websocket upgrade request. Feels hacky but works.
I'll now try to implement it for our website.

**Comment by rodja** [comment]
@Xtreemrus we just released a hotfix with PR #1300 to the public website. It looks good on my side. Can you please test and verify that the bug is really fixed?

**Comment by Xtreemrus** [comment]
> @Xtreemrus we just released a hotfix with PR #1300 to the public website. It looks good on my side. Can you please test and verify that the bug is really fixed?

Fixed :)

**Comment by rodja** [comment]
Thanks for going all the way @Xtreemrus. I'm happy you persisted in this. The new solution is much cleaner and better. It was quite an effort. But worthy.
