### ISSUE TITLE
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)' when packaging in native mode using PyInstaller

### ISSUE THREAD

**Issue by o12486vs2** [zauberzeug/nicegui#1264]
### Description

Hello,

I've encountered an issue while using pythonnet in my project, specifically when packaging in native mode using PyInstaller. The full error message is as follows:

```
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "nicegui\native_mode.py", line 42, in open_window
    webview.start(storage_path=tempfile.mkdtemp(), **globals.app.native.start_args)
  File "webview\__init__.py", line 154, in start
  File "webview\guilib.py", line 119, in initialize
  File "webview\guilib.py", line 71, in try_import
  File "webview\guilib.py", line 60, in import_winforms
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "webview\platforms\winforms.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 143, in load
  File "clr_loader\types.py", line 64, in __call__
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'
```

I have attempted several possible solutions, such as checking the pythonnet version, verifying environment variables, checking .NET framework version, and using a virtual environment. However, the issue still persists.

Could you please assist me in resolving this issue? Your assistance would be greatly appreciated. Thank you for your time.

Best regards,

**Comment by falkoschindler** [comment]
Please provide a [minimum reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). Does the packaging work without NiceGUI?

> specifically when packaging in native mode using PyInstaller

But it also occurs without packaging? Is the traceback from the packaging process or from running the app?

**Comment by o12486vs2** [comment]
Thank you for your response.

Here is a minimum reproducible example with the code I used:
from nicegui import app, ui, events
from fastapi.responses import RedirectResponse
import asyncio
import threading
import concurrent.futures
from functools import lru_cache
import time
from io import BytesIO
import os
import re
import datetime
import requests
import pandas as pd
import xlsxwriter
import json
import random
import urllib3
import base64
import warnings
from functools import partial

ui.label('some label')

favicon = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAABg1BMVEUAAADI6vm83O2WsMfI6vnH6fjO8f+ct8zI6vnE5vV5jqnI6vnI6vnH6fjG6PfG6PfQ8/+futAAAAD////H6fjH6fjG6Peuy99yhqNhcIosMzuqxdLG6PfG6PfI6/mlwdaDmrRUYoSBl7Xj//+btcp8ka3K7PvM7/2XschgcZF9kq262uzR9P/S9f7K7fuivtMhJ0sQEisAAADt//9pepnE5fXT9/+XschneJcAAACjvOVSXX6KoruUrcXW+v+ct81ugZ85Q2mXsciwzuAAAArY9/8AAAP////D5POJoLlFUXbR9P3R9P7C4/RneZZMWXkgJVDS9f+hvdK+3uSWsMdxhaIgJklFTW83PmWNpb3///+Bl7G52OotNVkKETGsw9UeJVAeI07e//91iaEAAAB1iaQYG0dBTHI6RGqVrsWFnLahvNEHCDfO8f7K7PvI6vnL7vzN8P7F5/bN7/652erH6Pexz+HN8P3D5PSz0eS83O2syd3B4fD///87BCLjAAAAcHRSTlMAAQUvBAKfrQUBBVfcggMiarv7/vQPAgNb5PiKMwIBA7b+3ZVLM5TeBAKTzWBGbbL4/vwnAQEgfJfwvGkGAgFnm/vSczYsqg8FAQE8vjdvzv50AgFn7U7WbyMCAQMGZtY9AQUCAQIsAwUBAQEBAgIBW/0iDQAAAAFiS0dEFnzRqBkAAADASURBVBjTY2DABRgZGJkYmOE8RkYWFlYGNnaYHAcjAycXN08BL4TPx8jALyAoVCgsIioG4oszSEgWFZeUSknLyMoBVcgzKJQplispq6iqqTNoMDBoMmhVaOvo6ukbGBoZM5gwMJiaVZpbWFZV11hZ29gy2AG12Ds41jo5u7i6uXt4eoFs8S7w8fXzD6gLZAgKBjsjJDSsPjwikiEqGuLImNi4+ASGRK+kZIYUiEgqQ1p6RmZWNswbOQy5efkMeAAA93kgidIoJUIAAAAASUVORK5CYII='
ui.run(native=True,window_size=(1200, 1200),fullscreen=False,favicon=favicon, title='InvestWings', reload=False)




And this is the code I used when building with PyInstaller:
import os
import subprocess
from pathlib import Path
import nicegui

cmd = [
    'python',
    '-m', 'PyInstaller',
    'test.py',
    '--name', 'InvestWings',
    #'--onefile',
    #'--windowed',
    '--add-data', f'{Path(nicegui.__file__).parent}{os.pathsep}nicegui',
]
subprocess.call(cmd)



I'm using version 1.3.5 of NiceGUI, Python version 3.8.9, and PyInstaller version 5.13.

The issue does not occur without packaging and the traceback is from running the app, not the packaging process.

I hope this information is helpful. Looking forward to your feedback.

**Comment by falkoschindler** [comment]
Thanks for the clarification, @o12486vs2!
It looks like you didn't even import pythonnet. So how can it be part of the traceback?
Apart from that, I guess the example is not minimal yet. What if you remove all these unused imports? What if you remove `ui.run` arguments like the favicon? Please try to reduce it to the bare minimum. This makes it much easier to find the root cause of the error.

**Comment by firai** [comment]
Pywebview uses pythonnet to load Webview2 on Windows

The error seems to suggest that the .NET CLR failed to load. What Windows version, pythonnet version and .NET runtime are installed? Is [Webview2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) installed? Are there any non-ASCII characters in the folder names?

**Comment by mq-evan** [comment]
Hi,

I've just encountered this issue and here's what I found!

The problem I was experiencing was the PyInstaller compiled .exe would run totally fine on my development machine, however on the target machine I would see either of the following errors:

`RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'`

or

`RuntimeError: Failed to resolve Python.Runtime.Loader.Initialize from C:\project\niceguiproject\pythonnet\runtime\Python.Runtime.dll`

From consulting various issue threads from [pythonnet](https://github.com/pythonnet/pythonnet/issues/1617), [pywebview](https://github.com/r0x0r/pywebview/issues/1215) and [VectorVein](https://github.com/AndersonBY/vector-vein/issues/60), I checked that the version of the .NET framework was identical on both machines, and changing versions of various packages (pythonnet and its dependencies) did not make a difference.

When running the .exe on the target machine for the first time, Windows would prevent the file from running, and you have to choose the "Run Anyway" option to proceed. This unblocks the .exe file, however it seems the problem is that the .dll file from pythonnet has not been unblocked.

So, to solve the issue, I had to unblock the .dll file, as described [here](https://www.tenforums.com/tutorials/5357-unblock-file-windows-10-a.html), either through right click -> properties or from running a PowerShell command. 

Also, compiling the .exe using the --onefile argument avoids this issue.

Hope this helps!
