### ISSUE TITLE
UI is not updated if await is used in callback

### ISSUE THREAD

**Issue by rodja** [zauberzeug/nicegui#131]
Reproduction:

```python
from nicegui import ui

async def open():
    with ui.dialog() as dialog, ui.card():
        l = ui.label('This should be visible')
    dialog.open()
    await asyncio.sleep(2)
    l.text = "New text after 2 seconds"
ui.button('Open a dialog', on_click=open)

ui.run()
```

I expect the dialog to open and show the text "This should be visible". After two seconds the text should change. But the dialog does not appear for two seconds at all. And then shows the final text.

**Comment by falkoschindler** [comment]
I think there is not UI Update happening until `open()` returns. Try adding an explicit update before sleeping.

**Comment by rodja** [comment]
Well... the dialog triggers an update (see https://github.com/zauberzeug/nicegui/blob/main/nicegui/elements/dialog.py#L27). But that seems to be not enough. It works if I run an update on the whole page (`dialog.page.update()`). Should we change the dialogs behaviour to update the whole page?

**Comment by falkoschindler** [comment]
I think I understand the problem:

The dialog is *created* in the click event handler. So even after updating the dialog, it is not shown, because its parent container needs an update with this new element. This only happens when leaving the event handler.

We can either add an explicit `create_task(dialog.page.update())` after creating the dialog, or - like we usually to it - create the dialog once in global scope and reuse it on click.

**Comment by falkoschindler** [comment]
The problem is larger: New elements are only sent to the client after leaving the callback handler, which is after sleeping for 2 seconds in this example.

```python
async def add():
    l = ui.label('This should be visible')
    await asyncio.sleep(2)
    l.text = 'New text after 2 seconds'

ui.button('Add label', on_click=add)
```

This is due to our "auto-context" implementation updating the UI when leaving the context of the current view, which happens at the end of an event handler: https://github.com/zauberzeug/nicegui/blob/18d7c625c45e3fd6182a92a30af4f9399e8cf0d9/nicegui/globals.py#L68-L75

**Comment by me21** [comment]
Thank you, `dialog.page.update()` helps. I assume for other use cases, without the dialog, but with other added UI elements, we still need to update the whole page.
