### ISSUE TITLE
AG Grid with Conditional Cell Formatting Example fails

### ISSUE THREAD

**Issue by williwehrlos** [zauberzeug/nicegui#1342]
### Description

Hello,

the Example from the Documentation "AG Grid with Conditional Cell Formatting" fails with the following error:

```
NiceGUI ready to go on http://localhost:8080, and http://192.168.0.21:8080
Cannot run JavaScript before client is connected; try "await client.connected()" or "client.on_connect(...)".
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\nicegui\functions\timer.py", line 92, in _invoke_callback
    await result
  File "c:\Users\xxx\Documents\Code\fwdashboard\tests.py", line 23, in format
    await ui.run_javascript(f'''
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\nicegui\functions\javascript.py", line 24, in run_javascript
    raise RuntimeError(
RuntimeError: Cannot run JavaScript before client is connected; try "await client.connected()" or "client.on_connect(...)".
```

Tested version is current 1.3.7

**Comment by falkoschindler** [comment]
Thanks for reporting this issue, @williwehrlos!
This demo was kind of outdated anyway, since Difusio on Discord [noticed](https://discord.com/channels/1089836369431498784/1131144216945369169/1131144216945369169) that conditional cell formatting simply works without any trickery.
So I fixed and simplified the demo in commit https://github.com/zauberzeug/nicegui/commit/50deb1139b4819a3bbba5603a9ba6a86b282c4f1.
