### ISSUE TITLE
Web pages generated by NiceGUI do not contain linkable anchor tags

### ISSUE THREAD

**Issue by metaperl** [zauberzeug/nicegui#136]
It is laudable that the NiceGUI website is implemented in NiceGUI itself. That being said, the anchor tags generated by NiceGUI do not have a name attribute and thus you cannot link to parts of a page generated by NiceGUI directly.

**Comment by falkoschindler** [comment]
If with "the anchor tags generated by NiceGUI" you refer to the result of `ui.link`: Yes, that's true. They are supposed to link *to* some other target, thus are not designed to be link targets themselves.

But you can easily place targets with `ui.html`:

```python
ui.link('Scroll to HTML', '#html')

for i in range(100):
    ui.label(f'Line {i}')

ui.html('<a name="html">HTML</a>')
```

Alternatively you can link to an arbitrary NiceGUI element, since they all have an ID contained in their JustPy view:

```python
top = ui.label('Top')

for i in range(100):
    ui.label(f'Line {i}')

ui.link('Scroll to Top', f'#{top.view.id}')
```

But I admit, this is not very "nice" and there could be an explicit API for it. What are you suggesting?

- Introducing a `ui.link_target(name=...)` element?
- Or allow using `ui.link()` without `target` but with `name`? I personally always found the HTML anchor tag confusing for serving two purposes.
- Target could also be a NiceGUI element itself: `ui.link(target=label)`. But it would be difficult to link somewhere further down the page if the target element is not yet defined.

**Comment by falkoschindler** [comment]
I simply added `ui.link_target(name=...)`.
