### ISSUE TITLE
ui.aggrid does not show values if there is a period in the column name

### ISSUE THREAD

**Issue by dashorty** [zauberzeug/nicegui#1417]
### Description

If there is a period in the Name column, the value of this column is not displayed.
I noticed when I wanted to normalize a JSON with panda.

Here is an example:
```python
import pandas as pd
from nicegui import ui


data = [
    {"id": 1, "name": {"first": "Coleen", "last": "Volk"}},
    {"name": {"given": "Mark", "family": "Regner"}},
    {"id": 2, "name": "Faye Raker"},
]

df = pd.json_normalize(data)
df2 = pd.json_normalize(data, sep="_")

ui.label("with period in the column name")
ui.aggrid.from_pandas(df)
ui.label("without period in the column name (sep=\"_\")")
ui.aggrid.from_pandas(df2)

ui.run(show=False)

```
![2023-08-14 12 05 09 localhost 59e593e7cf84](https://github.com/zauberzeug/nicegui/assets/2131900/d656f7c8-58c3-477b-9d34-65dc6ffde9d9)

**Comment by falkoschindler** [comment]
Thanks for reporting this issue, @dashorty!
I didn't even know that you can - in principle - use nested dictionaries for defining row data. But apparently we can't use column IDs with dots like in the following example:

```py
ui.aggrid({
    'columnDefs': [{'headerName': 'First name', 'field': 'name.first'}],
    'rowData': [{'name.first': 'Alice'}],
})
```

That's because AG Grid tries to access `rowData[0]['name']['first']` instead of `rowData[0]['name.first']`.

I'm not sure if this is a bug in NiceGUI or rather a limitation of AG Grid. Maybe NiceGUI should warn about column IDs containing dots? What do you think, @dashorty? Do you have an idea in mind how to approach this?

**Comment by dashorty** [comment]
I think a warning at runtime and/or a note in the documentation would be sufficient.

**Comment by falkoschindler** [comment]
Ok, commit [c6ad97a](https://github.com/zauberzeug/nicegui/commit/c6ad97a693f44d95109f6625cd5cfeee481c7b78) adds such a warning.
Commit [3f4f2cf](https://github.com/zauberzeug/nicegui/commit/3f4f2cff00e3347c630b9bf985959a81824b7b75) adds a demo with complex objects in an AG Grid.

**Comment by firai** [comment]
According to https://stackoverflow.com/questions/58772051, it's possible to show field names with dots by suppressing Aggrid's parsing for nested structures

**Comment by falkoschindler** [comment]
Thanks for the hint, @firai!
So should we simply set `suppressFieldDotNotation` instead of showing a warning?

**Comment by firai** [comment]
> So should we simply set `suppressFieldDotNotation` instead of showing a warning?

It seems to me that having dots in the field names would be much more common than trying to display nested json structures, so I would think so. But as soon as I say that, I'm sure we'll get this: https://xkcd.com/1172/

**Comment by falkoschindler** [comment]
Ok, in [325dfcd](https://github.com/zauberzeug/nicegui/commit/325dfcdcd56eb195a9efd9bd49bc5c4aca17901c) I set the `suppressFieldDotNotation` option instead of showing a warning. That should work in basically all cases.
I also added the possibility to pass additional options to the `from_pandas` method. So the user could overwrite this flag.

**Comment by firai** [comment]
Does the complex object demo that you added need to explicitly set the flag to `false` then?

**Comment by falkoschindler** [comment]
@firai I don't think so, because it doesn't use `from_pandas`.
