### ISSUE TITLE
Number Input fails on float conversion

### ISSUE THREAD

**Issue by bergmansj** [zauberzeug/nicegui#1479]
### Description

Using the basic number input example from the docs:
```python
from nicegui import ui

ui.number(label='Number', value=3.1415927, format='%.2f',
          on_change=lambda e: result.set_text(f'you entered: {e.value}'))
result = ui.label()

ui.run()
```
When you empy out the input field (or even use backspace to make '3.' from '3.14') the following error appears on the console:
```
could not convert string to float: ''
Traceback (most recent call last):
  File " <snip> /venv/lib/python3.10/site-packages/nicegui/events.py", line 373, in handle_event
    result = handler(arguments) if expects_arguments else handler()
  File " <snip> /venv/lib/python3.10/site-packages/nicegui/elements/mixins/value_element.py", line 30, in handle_change
    self.set_value(self._event_args_to_value(e))
  File "  <snip>  /venv/lib/python3.10/site-packages/nicegui/elements/number.py", line 97, in _event_args_to_value
    return float(e.args)
ValueError: could not convert string to float: ''
```
(local paths snipped)

This was introduced somewhere after v1.3.6 (that version has a different `_event_args_to_value` implementation that checks for an empty string)

**Comment by falkoschindler** [comment]
Here I introduced the bug while "fixing some mypy issues":

https://github.com/zauberzeug/nicegui/commit/a55a452a1cb5e4bb7d72f84e3d3bef0074de07be#diff-876b4c6ca305085724524c58b88f3685057fb0a803275d6957375205a96dfb17

When removing all characters from the number input, the value becomes `''` instead of `None`.
I fixed the condition in [a001cab](https://github.com/zauberzeug/nicegui/commit/a001cab51cd1a11714dd3f04c205f8afc3a493cc).
