### ISSUE TITLE
Replacing draggable 3D objects breaks DragControls

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#1505]
### Description

Replacing draggable objects in `ui.scene` can cause JavaScript errors that lead to an inconsistent state on the server. Consider the following example of four colored spheres:

```py
def replace():
    scene.delete_objects(lambda obj: obj.color in {'red', 'green'})
    scene.sphere().draggable().move(0).material('red')
    scene.sphere().draggable().move(1).material('green')

with ui.scene(on_drag_end=replace) as scene:
    scene.sphere().draggable().move(0).material('red')
    scene.sphere().draggable().move(1).material('green')
    scene.sphere().draggable().move(2).material('blue')
    scene.sphere().draggable().move(3).material('yellow')
```

When dragging the first sphere (red) and trying to drag the second one afterwards (green), there is the following JavaScript error in the console:
```
Uncaught TypeError: Cannot read properties of null (reading 'matrixWorld')
    at HTMLCanvasElement.onPointerDown (DragControls.js:164:44)
onPointerDown @ DragControls.js:164
```
When releasing the mouse, there is a KeyError in Python:
```
'4f3ba817-9468-4d92-97e0-af7b74b528de'
Traceback (most recent call last):
  File "/Users/falko/Projects/nicegui/nicegui/events.py", line 383, in handle_event
    result = handler(arguments) if expects_arguments else handler()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/falko/Projects/nicegui/nicegui/elements/scene.py", line 156, in handle_drag
    self.objects[arguments.object_id].move(arguments.x, arguments.y, arguments.z)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: '4f3ba817-9468-4d92-97e0-af7b74b528de'
```

The problem also occurs when `replace()` is triggered via a button after dragging the first sphere. But using `on_drag_end` simplified the example.

**Comment by kalle264** [comment]
I think I found the problem. Will provide a detailed answer later today

**Comment by kalle264** [comment]
In short, the wrong objects are deleted from the draggable_objects array in scene.js. The current code in delete() and draggable() is:
`this.draggable_objects.pop(this.objects.get(object_id));`
but Array.pop() always removes the last object and doesn't take any parameters.
I think you can't delete from an array by value, you have to get the index first. 
```
let index = this.draggable_objects.indexOf(this.objects.get(object_id));
if (index != -1) this.draggable_objects.splice(index, 1);
```


I found that the key from the Python KeyError is either the key of the first spawned green or the red sphere, which shouldn't exist anymore since they are replaced after the dragging.
The click_handler in scene.js gets the correct ID of the new sphere, but the ID in the 'dragend' event received by Python is wrong.
When the error occurs, the parent of the selected variable in DragControls is null, causing the TypeError in JavaScript.
When printing the IDs of the objects used in the raycaster in onPointerDown, I saw that the wrong ones are deleted.

Before dragging
```
00ff84a5-b4d6-4d06-ab7d-f5d8816d6077 - red
a7ccbf95-60a1-414d-bf63-79048698424d - green
0a083eb8-4e1b-4010-8ac7-5768250de51c - blue
e7b780c6-6ed6-4c43-b032-ec81b2420e6a - yellow
```
After running the replace function
```
00ff84a5-b4d6-4d06-ab7d-f5d8816d6077 - red
a7ccbf95-60a1-414d-bf63-79048698424d - green
7269ee84-406b-4e70-a52b-1c3617158334 - new_red
f911d423-5516-4796-95fb-f22252e770bf - new_green
```
And this leads to the draggable_objects.pop mistake described at the top, since the array is only modified there.

I will post a pull requests to fix it.
