### ISSUE TITLE
nicegui doesn't work on ipad running iOS 12.5.7

### ISSUE THREAD

**Issue by Dan1001** [zauberzeug/nicegui#1506]
### Description

Hi,

I've an old ipad running iOS 12.5.7. A simple nicegui demo application works fine on desktop, and on a modern iPhone. But on the iPad I just get a blank screen, titled "nicegui" but with no content. The nicegui app shows that the iPad accessed it (giving errors for not finding apple-touch-icon.png). But the iPad browser (safari or Chrome) shows nothing.

Help would be appreciated!

**Comment by falkoschindler** [comment]
Hi @Dan1001, thanks for reporting this issue, and sorry for the late reply!
Just for completeness, what does your demo application look like? Anything else than the hello-world example from https://nicegui.io/#installation?
Can you get into some kind of JavaScript developer console? Are there any errors or warnings?

**Comment by falkoschindler** [comment]
I just reproduced this error with a simply Hello World app on an iPad with iOS 12.5.5.
To get into the JavaScript console, I followed this instruction: https://stackoverflow.com/a/15298016/3419103.

It seems like TailwindCSS doesn't work on such an old OS. JavaScript says "SyntaxError: Unexpected token '.'" when loading tailwindcss.min.js. When running NiceGUI with `ui.run(..., tailwind=False)`, the page loads normally, but - of course - without TailwindCSS. On an older [discussion](https://github.com/tailwindlabs/tailwindcss/discussions/6814#discussioncomment-1891290) I found that they don't target iOS 13 or less.

So I conclude that we won't be able to fix this issue, since it is caused by Tailwind. As a workaround, you can disable Tailwind. Alternatively you can try to serve an old tailwindcss.min.js.

**Comment by falkoschindler** [comment]
Another similar discussion for reference: https://discussions.apple.com/thread/254888504
