### ISSUE TITLE
QInput validation causes not responding page

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#151]
Firstly, I apologize if it doesn't belong to NiceGUI.
I tried to add input validation to input control as per https://v1.quasar.dev/vue-components/input#internal-validation
```
ui.input('Step name').props('dense :rules="[val => !!val || \'Field is required\']"')
```
However, this code causes CPU load in the browser and the page is not responding.

**Comment by falkoschindler** [comment]
Very interesting!

It looks like the rules are not properly parsed by NiceGUI, because ":" is not a [word character](https://github.com/zauberzeug/nicegui/blob/e4e78895c862fc91bf5b40558845d2ae2235628b/nicegui/elements/element.py#L76). But even if I add the colon, we get an invalid attribute name.

So I looked into JustPy and found how to set [internal validation rules](https://justpy.io/quasar_tutorial/quasar_components/#qinput-internal-validation-with-rules). It looks promising, but somehow it is not working with NiceGUI's version of JustPy. This is due to a [typo](https://github.com/justpy-org/justpy/issues/365), which I haven't fixed in our JustPy fork until [now](https://github.com/zauberzeug/nicegui/commit/303b3da458ddfa5256306bb80b35ae1c888598d3).

Now you can write validation rules as follows:

```python
i = ui.input('Name')
i.view.rules = ['(val) => (val.length <= 3 || "Please use maximum 3 characters")']
```

**Comment by fuxionline** [comment]
> Now you can write validation rules as follows:
> 
> ```python
> i = ui.input('Name')
> i.view.rules = ['(val) => (val.length <= 3 || "Please use maximum 3 characters")']
> ```

It looks like the validation rule example doesn't work anymore --> AttributeError: 'Input' object has no attribute 'view'
Any idea how to fix this?

**Comment by falkoschindler** [comment]
@fuxionline Thanks for pointing this out! The possibility for defining validation rules got lost when we transitioned from version 0.9 to 1.0 and removed JustPy as the underlying framework. This is why our elements have no `view` anymore.

I created a new issue #336 to re-implement this feature.
