### ISSUE TITLE
Actual type of e.args does not match type hint for knob update:model-value

### ISSUE THREAD

**Issue by AndrewMHenry** [zauberzeug/nicegui#1518]
### Description

# Summary

Interacting with the knob in the example below shows that the type of `e.args` is `float`, while the type hint given for `GenericEventArguments` is `Dict`.

Any easy workaround could be to loosen the type hint to `Any`, although that has its own drawbacks.

# Minimal example

```python
from nicegui import ui
from nicegui.events import GenericEventArguments


knob = ui.knob(value=0.5, color="blue", show_value=True)
with ui.grid(columns=2):
    ui.label("The type of GenericEventArguments.args is:")
    ui.label(str(GenericEventArguments.__annotations__["args"]))
    ui.label("But the type of e.args is:")
    type_label = ui.label()


def on_change(e: GenericEventArguments) -> None:
    type_label.set_text(str(type(e.args)))


knob.on("update:model-value", on_change)

ui.run()
```

**Comment by falkoschindler** [comment]
Thanks for bringing this up, @AndrewMHenry!

You're right, some events come with string or float `args`, so the type annotation wasn't correct.
I simply followed your suggestion and changed it to `Any`, because that's exactly what it is. If a consumer callback wants to get better type safety, it can always assert or cast to a more specific type:
https://github.com/zauberzeug/nicegui/blob/3b3aed247f88374218ea336d90a94a18c1941455/nicegui/elements/interactive_image.py#L42

**Comment by AndrewMHenry** [comment]
@falkoschindler Sure thing; thanks for fixing this so quickly!
