### ISSUE TITLE
Context menu does not appear at the touch position

### ISSUE THREAD

**Issue by gavinpotter** [zauberzeug/nicegui#1738]
### Description

The context menu does not appear at the touch position despite the touch position being set in the example . It appears below the containing element. This can be seen on the [example on nicegui.io](https://nicegui.io/documentation/menu#custom_context_menu).  I've tested it both with Chrome and Edge.

```py
with ui.image('https://picsum.photos/id/377/640/360'):
    with ui.menu().props('context-menu touch-position'):
        ui.menu_item('Flip horizontally')
        ui.menu_item('Flip vertically')
        ui.separator()
        ui.menu_item('Reset')
```

**Comment by falkoschindler** [comment]
Thanks for bringing this up, @gavinpotter!
As far as I remember, when writing this demo, I just couldn't figure out why the menu is not at the mouse position. Eventually I gave up and left it like this. But maybe someone has an idea and can help to finally fix this glitch. 🙂

**Comment by natankeddem** [comment]
@falkoschindler had some workarounds posted here https://github.com/zauberzeug/nicegui/issues/747. The generic element variant worked for me.

In terms of fixing the issue it looks like QMenu doesn't like registering the `update:model-value` event for some reason? As soon as I comment out:
https://github.com/zauberzeug/nicegui/blob/06ee5c4bf8b0a0ef226a3cc5af658d0c4691fc62/nicegui/elements/mixins/value_element.py#L32
It works correctly.

**Comment by falkoschindler** [comment]
Very interesting, @natankeddem! Your deduction seems to be correct.

Here is, however, a counterexample:
```py
with ui.image('https://picsum.photos/id/377/640/360').classes('w-96'):
    with ui.element('q-menu').props('context-menu touch-position') as menu:
        ui.menu_item('Copy')
        ui.menu_item('Delete')

menu.on('update:model-value', ui.notify)
```
Even though we register an update handler, the menu is placed correctly. 🤔

**Comment by gavinpotter** [comment]
Yes - That works very nicely.  Thanks for the very quick response and workaround.

**Comment by itsayopapi** [comment]
maybe this can help

from nicegui import ui

with ui.image('https://picsum.photos/id/377/640/360') as img:
    img.style('position: relative;')  # Add relative positioning to the image container
    with ui.menu().props('context-menu'):
        ui.menu_item('Flip horizontally')
        ui.menu_item('Flip vertically')
        ui.separator()
        ui.menu_item('Reset')

# Add your original  CSS to position the context menu at the touch position
ui.css('.context-menu {position: absolute; left: var(--nicegui-touch-x); top: var(--nicegui-touch-y);}')

ui.run()

**Comment by falkoschindler** [comment]
@itsayopapi Even if I replace `ui.css` (which doesn't exist) with an expression based on `ui.add_head_html`, this doesn't work on my machine. But I'm also not sure what `--nicegui-touch-x` is supposed to be.

**Comment by natankeddem** [comment]
@falkoschindler 
Okay, I think I have a theory as to what is going on. `ValueElement` initially sets the prop `model-value` on instantiation of the element. It then loops back the value of `model-value` when it gets an `update:model-value` event. So, what I am thinking is that giving the menu a `model-value = true` during the loop back is forcing the menu open without looking at the mouse position. Which sort of makes sense because it wasn't the mouse that opened the menu but the change in `model-value` in the props.

**Comment by itsayopapi** [comment]
@falkoschindler 
 --nicegui-touch-x is used to represent the horizontal (X-axis) position of the touch event on the screen. It's likely a variable defined and used internally by the nicegui library to manage touch events and positions.
 
 --nicegui-touch-x is a custom CSS variable that holds the X-axis position of a touch event, and it's used to dynamically position elements (in this case, the context menu) based on touch input.


this is how it works

The nicegui library internally sets the value of --nicegui-touch-x to the horizontal position of the touch event on the screen when a touch event occurs.

In your custom CSS rule for the context menu, you use var(--nicegui-touch-x) to access the value of --nicegui-touch-x and set the left property of the context menu element to that value. This effectively positions the context menu horizontally at the touch event's X-axis position.

**Comment by falkoschindler** [comment]
@itsayopapi It sounds like `--nicegui-touch-x` already exists in the NiceGUI library. But if there was such a CSS variable, I would certainly have heard about it. 😉
_In case_ you copy-pasted AI-generated code (it looks like it), please add a disclaimer. Otherwise it can cause quite some confusion among us humans. 😄

@natankeddem That's a great explanation! I already tried setting `ui.menu.LOOPBACK = False` before instantiating the menu, but then it doesn't open at all. I might need to dig a bit deeper and refresh my knowledge about the internal workings...

**Comment by natankeddem** [comment]
@falkoschindler setting it False will keep it closed forever.  As an experiment try commenting out the set on instantiation and the loop back portion.

**Comment by falkoschindler** [comment]
Here is a minimum reproduction I found without using `ui.menu` or `ValueElement`:

```py
with ui.card().classes('w-96 h-32'):
    with ui.element('q-menu').props('touch-position') as menu:
        menu._props['model-value'] = False  # works without this line
        menu.on('update:model-value', lambda: None)  # also works without this line
        ui.menu_item('Menu')
```

The code causes the menu to remain closed. But if you remove either of the commented lines, the menu appears right where it should. (Note that I removed the "context-menu" prop for easier testing, so you can left-click the card.)

My vague explanation is: If you register an event handler on a QMenu with "touch-position" prop, it doesn't open automatically. Only since our `ValueElement` loops back the event, the menu appears. But since the touch position isn't transmitted, all the menu can do is to open at some default position.

But I still don't get why initializing the "model-value" to `False` changes the behavior.

**Comment by natankeddem** [comment]
I know it might be too big of a deviation but there is always the `show` and `hide` methods and their associated events which could be utilized instead of `model-value` I believe.

**Comment by falkoschindler** [comment]
Well, if we deviate from `ValueElement`, we could as well re-implement a simple `ui.context_menu` element without bells and whistles like this:

```py
class ContextMenu(ui.element):

    def __init__(self) -> None:
        super().__init__('q-menu')
        self._props['context-menu'] = True
        self._props['touch-position'] = True

with ui.image('https://picsum.photos/id/377/640/360').classes('w-96'):
    with ContextMenu():
        ui.menu_item('Copy')
        ui.menu_item('Delete')
```

We could add a warning when someone tries to use `ui.menu` with the "touch-position" prop, like we did for `ui.tree` with "default-expand-all" here: https://github.com/zauberzeug/nicegui/blob/4cd74756a6ebaa6b7387d6cac67481caed48f6a1/nicegui/elements/tree.py#L104-L108
