### ISSUE TITLE
Tailwind text colors set via ".classes" selectively don't work for buttons

### ISSUE THREAD

**Issue by Rinzlov** [zauberzeug/nicegui#1821]
### Description

Trying to specify text color via ".classes" selector works well for labels and other elements but doesn't work for buttons when the color has a specified hue as can be seen on examples below:

Example code:
```py
from nicegui import ui

def main():
    ui.label('Label color works').classes("text-red-400")
    ui.button("Button color doesn't work").classes("text-red-400")
    ui.button("Unless it's pure color").classes("text-red")
    ui.run()

if __name__ in {"__main__", "__mp_main__"}:
    main()
```
Result:
![image](https://github.com/zauberzeug/nicegui/assets/1098586/37533911-dee2-4739-822c-6463cbb969ab)

### For a label the "text-red-400" tailwind class works:

![image](https://github.com/zauberzeug/nicegui/assets/1098586/b0f01da1-3f8d-43dc-9dd4-724af6d83c6c)

### For a button, the same class doesn't work:

![image](https://github.com/zauberzeug/nicegui/assets/1098586/d6602b35-efdd-43c9-86ae-b8f0898506f8)

### Although this way it works:

![image](https://github.com/zauberzeug/nicegui/assets/1098586/cb5d63b8-3aea-4d62-aed1-1a333a894d53)

**Comment by Rinzlov** [comment]
Thank you for quick response.
This works for this use case but is there a general solution for other cases? I am guessing for other classes there won't be parameters that can be set to None.
My guess is that if it was easy to make all tailwind classes override the default styling of the component then it would already have been implemented? If not then maybe there could be a general UI setting "override_default_styles_with_the_ones_provided"?

I tried to use "replace" and "remove" options within the ".classes" and ".props" methods but had no luck so far. They are described in the documentation with "All three functions also provide remove and replace parameters in case the predefined look is not wanted in a particular styling." but I'm not sure if they can affect the default quasar styling?

**Comment by natankeddem** [comment]
I am not sure what other cases you are referring to? We can try to handle them one at a time if you want to elaborate on them.

I am not a maintainer but, I would assume some of these elements have a `color` argument to allow a "Nice"™ default state to be used with `ui.colors`. As for why you can't remove those classes manually? NiceGUI can only remove classes that it inserted directly. In this case the `color` attribute actually propagates down to a quasar element `prop` for the button not a class. The prop then inserts those classes via quasar. Therefore instead of doing `color=None` you can also just remove the `color` prop.
```py
from nicegui import ui

def main():
    ui.label("Label color works").classes("text-red-400")
    b = ui.button("Button color works with more steps").props(remove="color").classes("text-red-400")
    ui.button("Unless it's pure color").classes("text-red")
    ui.run()

if __name__ in {"__main__", "__mp_main__"}:
    main()
```

**Comment by falkoschindler** [comment]
<details>
<summary>
Maybe I can give some background to the problem with button colors:
</summary>

Originally we didn't have the `color` argument in `ui.button`. For setting a color, you had to use Quasar's `color` prop. But this is limited to Quasar colors, no Tailwind and no CSS.
And since we wanted the button to appear with primary color by default, we already set the prop to "primary", which Quasar translates to some CSS "background-color: ... !important". If you now wanted to change the background color using Tailwind classes or CSS definitions, you had to fight against the "!important" suffix.

Therefore we decided to introduce the `color` parameter, which accepts CSS, Tailwind as well as Quasar colors and cares about setting the corresponding props and classes.

Unfortunately this doesn't always behaves as expected. E.g. when placed on dark background, Quasar's automatic text color selection breaks:
```py
with ui.header():
    ui.button('Click me!', color='white')
ui.button('Click me!', color='white')
```

![Screenshot 2023-10-18 at 17 14 35](https://github.com/zauberzeug/nicegui/assets/5767091/3486c248-5ae2-4038-a3e0-823f2fc987ad)

So I'm still looking for a way to improve this button color issue.
</details>

But after this divagation about background colors, let's get back to the problem with text colors:

The difference between "text-red" and "text-red-400" is, that "text-red" is a Quasar color which directly impacts Quasar's color logic and can overwrite Quasar's default value, but "text-red-400" is a Tailwind class which looses against Quasar in this respect. But you can enforce it with an "!important" prefix like this:
```py
ui.button('Works').classes('!text-red-400')
```

I wonder if we need something mildly intelligent like the `color` parameter, but for the text color. The problem is, that the "color" becomes a "text color" if setting the "flat" prop. What a mess. 🤯

**Comment by Rinzlov** [comment]
Thanks @natankeddem for your help.
Thanks @falkoschindler for tuning in, I tried to be a good user and to dive in a little bit and propose something but after a long while I realised I can't spend too much time on this now...
I will try to do that in the future as this library looks very promising.
I started digging into some issues reported in quasar repo and see that as long as they don't change the approach it will be very difficult to fixt these sort of issues in downstream libraries like nicegui (there are others with same type issues as I see).

It may be good to mention these limitations in the documentation in tailwind section.

**Comment by falkoschindler** [comment]
@anatoli26 Let me share a response from claude.ai which is pretty much spot-on:

> This is a great observation about NiceGUI and Tailwind CSS interaction. The issue you're encountering has to do with CSS specificity and how NiceGUI components handle styling.
> 
> The reason your first example doesn't work is because NiceGUI components typically have their own internal styling that takes precedence over Tailwind classes due to CSS specificity rules. In CSS, more specific selectors override less specific ones, and NiceGUI's internal styles are often more specific than your applied Tailwind classes.
> 
> Your second approach with `.props(remove="color")` works partially because you're removing the built-in color property, allowing your background colors to take effect, but the text color hover state still conflicts with other internal styles.
> 
> The third solution with the `!` important prefix works completely because it uses CSS's `!important` flag to override any other styling regardless of specificity.
> 
> As for why NiceGUI doesn't automatically prepend everything with the important prefix - there are a few good reasons:
> 
> 1. **Predictability**: Automatically adding `!important` to all classes could lead to unpredictable behavior when mixing with other CSS.
> 
> 2. **Flexibility**: Some users might want to keep certain NiceGUI styling while overriding others.
> 
> 3. **CSS Best Practices**: Overusing `!important` is generally considered bad practice as it breaks the natural cascading nature of CSS.
> 
> 4. **Performance**: Adding the prefix to every class would require additional processing.

I don't think performance is a big deal. My main argument would be "CSS Best Practices": We experience quite some challenges because Quasar is adding lots of `!` important prefixes. If everyone does it, nothing is predictable anymore. Or:

> “If everything is important, then nothing is.”
― Patrick M. Lencioni

**Comment by evnchn** [comment]
As I was saying in #4563 

1. You look and see if the NiceGUI element itself has such adjustment
2. If not, you look and see if the Quasar element the NiceGUI element is based on has such adjustment
3. If not, you look and see if the Tailwind CSS has such adjustment
4. If not, you set it via CSS [Then stuff gets markedly harder from here]

**Comment by evnchn** [comment]
TL-DR: Personally I do not advocate for the `force: bool = False`, let alone making all `.style` and `.classes` and `.tailwind` to be `!important`, due to compatibility concerns, inherent layered nature of NiceGUI, promoting the use of reasonable defaults, as well as the fact that (1) normal users don't use it while (2) power users will already use `!important` in their code. 

--

Consider: 
1. If `!important` is default behaviour, may break compatibility?
2. If `!important` is not default behaviour, and applied via `force: bool = False`, the convenience factor isn't that large?

I think, the fact that **NiceGUI is built on top of Quasar built on top of Tailwind built on top of plain CSS, and that we should look from top-layer to bottom-layer if we want UI changes**, can go somewhere in the docs / FAQ. Better awareness over the situation is perhaps better than opening the floodgates to easy use of arbitrary styles, as that isn't a good thing. 

One of the goal of NiceGUI is to provide "[reasonable defaults](https://nicegui.io/#styling)", otherwise might as well go use [JustPy](https://justpy.io/) [(Although we liked the approach, it is too "low-level HTML" for our daily usage.)](https://nicegui.io/#why). Allowing `force: bool = False` may bring the forced styles too easily to the library user's list of options. As we know, that's not exactly a good thing. It may turn into https://badhtml.com/. 

Anecdotally, I have seen some friends of mine mess up the styles of NiceGUI real bad, since they did not know that they can do what they want with native NiceGUI functonalities / Quasar functionalities / Tailwind functionalities, and went straight for CSS override rules. I'd wish that happens less. Really, if I were to design NiceGUI, I would probably put the ability to add arbitrary styles in `.__styles__` so that it is obvious you are not supposed to set it unless you absolutely have to. 

Also, from #4506, we see that many sites get away with the default styling. Fact is, styling was not in a lot of people's minds (not in mine, initially, too!). And, if you are so determined to do custom styling, you probably don't mind adding `!` or `!important`?

So, to me, `force: bool = False` is more of a convenience method, not enabling something new. And I personally want to withheld the convenience so that NiceGUI stays, y'know, Nice 😉

---

*I'll say, I may be biased, since I used NiceGUI for quite some time (joining circa v2.3.0 days), so I may not understand your struggles. I'm all ears, though.

**Comment by evnchn** [comment]
Final note: I don't believe "to make the styles specified with styles() and/or .tailwind() method to have priority over everything else" is "a simple option to solve all this". I have just cited compatibility and user behaviour guidance concerns in my above response. 

Fact is, I don't believe _anyone_ if they say they have a "simple solution to solve all problems". Just too good to be true. Whoever says this in real life may be scamming you money, just so you know...

---

Well, I would recommend you to join the contributors of this library, and get your hands dirty. "Those whose hands are clean are wrong" is one of my favorite quote of mine, but I can't find the source! Perhaps you can come up with something, and produce a demo similar to https://github.com/streamlit/streamlit/issues/10895*

I personally think you don't need tons of experience**, just a spirit of getting things done. Well I don't have experience, to say the least 😅. I myself begun contributing to NiceGUI and to public GitHub repositories less than a month ago, in fact. My first PR is on March 9, 2025. 3 days later will be my first-month anniversary. 

---

*Streamlit's implemeting flex layout beginning 2 weeks ago (Mar 25, 2025)? 🤡 

NiceGUI has flex layout as defaul since v1.4.0 (https://github.com/zauberzeug/nicegui/releases/tag/v1.4.0) on Oct 23, 2023

**Hardly true for other libraries! Their issues tab is crazy!! Their codebase is even crazier!!!

**Comment by evnchn** [comment]
Out the window, would say, by my logic, no, when you do "bg-teal-400" and it doesn't work, it's not a surprise. Since button offers `color`, you would check and use that first. 

Though, I shall grant, specifically the `ui.button` seems to be most "annoying" in terms of usage, by having you set the background color like this. Noting how most other elements don't offer `color` option natively, it means if I want to apply the same style to a variety of elements, either (1) I check the signature of `ui.button`, and make an exception for the button and pass in the native `color` option or (2) I do `!bg-teal-400` always. 

I'm saying this because I faced this issue first-hand while trying to make my first colored button in NiceGUI, but I understand that it is complicated to allow both `ui.button(color=)` and while set via `.classes`, so I understand the library's pain and went with it, while also establishing my internal "NiceGUI->Quasar->Tailwind->CSS" sequence rule circa then. 

Checking the calling signature of an element before using it is recommended, but it may not be intuitive if we _have_ to do it to get what we want. 

We could think about how we can potentially rework `ui.button`, but I don't think we should rework the `.classes` just for the button. It would also be quite overkill to modify the behaviour of a method which applies to all elements, when we only face trouble with `ui.button`

---

You have mentioned you want to create custom components, and style everything. 

I must bring light to you `.default_classes`, `.default_props` and `.default_styles`. https://nicegui.io/documentation/element#default_props https://nicegui.io/documentation/element#default_classes https://nicegui.io/documentation/element#default_styles. 

Styling the first button may be tough, but with the above, at least you do it once and once only. 

You can also have a function `def make_custom_button(text_in):` which returns an already-styled button, and similar helpers.

**Comment by falkoschindler** [comment]
I feel your pain @anatoli26! We've always had problems with coloring buttons. The `color` parameter should make it easier, but somehow it even adds to the confusion.

There's been a similar problem with padding in `ui.card`. Quasar's CSS rules made it very difficult to built NiceGUI's layout system on top. In PR #3444 we finally solved it by manipulating Quasar's CSS via JavaScript:
https://github.com/zauberzeug/nicegui/blob/637e79585638daf2a2b02890b20105af5c4718fa/nicegui/static/nicegui.js#L438-L445

Maybe there's a similar solution for buttons. We should check if there are any negative side effects, but maybe we can remove Quasar's "!" important marker from this specific rule.

**Comment by falkoschindler** [comment]
For reference, in #4415 we see an excerpt of quasar.css and its `!important` madness. There I refused to modify Quasar's default behavior. But if we better understand the implications, it might be a viable solution - maybe for NiceGUI 3.0 due to breaking changes. I'm struggling to find an explanation for why they chose to do it this way.

In https://github.com/quasarframework/quasar/issues/5566 we see how Quasar encourages to set custom colors: Define a new "text-" or "bg-" class and apply it to the UI element. This doesn't seem viable for NiceGUI because every new color would need to add new CSS definitions.

**Comment by evnchn** [comment]
Remind me to put this in context for #4621 when I have time to use a computer. 

Remind me to ship a Middleware which strips !important from Quasar CSS on-demand, and setup a poll inviting people to try their site with/without the middleware to assess the impacts of NiceGUI stripping !important from Quasar starting 3.X onwards. 

You can take on these tasks if you are bored, too!
