### ISSUE TITLE
Unexpected behaviour when function decorated with @ui.refreshable

### ISSUE THREAD

**Issue by gavinpotter** [zauberzeug/nicegui#1845]
### Description

If you call a function which is decorated with ui.refreshable it does not return anything.  If you call the same function without it being decorated then it returns as expected.
A minimal reproducible code example is shown below:
```py
from nicegui import ui

@ui.refreshable
def CreateLabel1(text):
    return ui.label(text)
    
def CreateLabel2(text):
    return ui.label(text)   
     
label1 = CreateLabel1("Hello world")
print("Return object from CreateLabel1",label1) 

label2 = CreateLabel2("Hello world")
print("Return object from CreateLabel2",label2)   
    
ui.run()    
```
The output returned is shown below:

Return object None
Return object <nicegui.elements.label.Label object at 0x0000027813C81110>

The documentation does not make this clear.  The documentation does say then when you call refresh() nothing is returned, but not when you simply call the function.  I think either this should be made clear in the documentation or  ideally, I'd prefer if you could return whatever the function is designed to return whether the function is decorated or not.  And as a feature enhancement, I'd prefer it if the function also returned what its return statement suggests when the refresh method is called as otherwise you lose the reference to the object.

The workaround is to do this:
```py
@ui.refreshable
def CreateLabel1(text):
    global label1
    label1 = ui.label(text)
```
but its not very elegant.

**Comment by falkoschindler** [comment]
Thanks for bringing this up, @gavinpotter!

Actually I never thought about the return value of refreshables... If you return a UI element, I assume the reference will be outdated as soon as the UI is refreshed, because everything inside is regenerated. Returning other things than UI elements might be useful though.

Can you explain your use case? What do you want to do with the returned element? Understanding the application might help to decide whether we try to support return values or warn about them.

**Comment by gavinpotter** [comment]
My use case is that I have a function to which i pass a set of nodes that updates a tree in the refresh function.  The user has the ability to change the nodes in the tree by adding, deleting nodes etc.  The refresh function then makes some changes to the nodes to aid their display and refreshes the tree with the new set of nodes. Ideally I'd like the reference to the tree to be passed back again so that the information at the nodes can be accessed by a number of back end functions.  There are a number of possible workarounds in my case.

However, more generally though, its not pythonic for a decorator to alter what happens within a function - it took me quite a long time to work out what was going on and alter my code to overcome this behaviour.  Its unexpected, and therefore might cause problems for other people, especially those who might return non ui elements in the refresh function.

**Comment by falkoschindler** [comment]
Thanks for the clarification!

> Ideally I'd like the reference to the tree to be passed back again so that the information at the nodes can be accessed by a number of back end functions.

In general it might be advisable to keep a reference to the raw data for backend functions instead of relying on the UI element. Then the backend doesn't have to care about the UI representation and the frontend (the refreshable in this case) can re-create UI elements based on the model data it has been given.

> its not pythonic for a decorator to alter what happens within a function

That's a good point. We'll see what we can do to fix the behavior of the decorator.

**Comment by gavinpotter** [comment]
Normally, I'd agree with you about keeping a reference to the raw data, but in this case, the backend needs to know which nodes are selected and expanded etc, which is easiest by just referencing the ui tree. It doesn't matter too much, because, as I said, early I can just keep a global reference to it, but - I think nicegui is by far the best python library I've come across for building front ends, and if I've found a need for the back end to be able to access a ui element directly from the backend, I'm sure others will have other use cases for doing it as well - hence the request for the refresh method to be enable the function to return the new ui element.
