### ISSUE TITLE
Styling <input> tags

### ISSUE THREAD

**Issue by adarshpunj** [zauberzeug/nicegui#1884]
### Description

```python
ui.input().style("color:white")
```
Or any other styling doesn't make a difference. Is it a known issue? I also tried using tailwind classes inside `.classes()`. 

So basically, the input element looks the same regardless of adding styling or classes.

**Comment by falkoschindler** [comment]
Hi @adarshpunj, the `ui.input` element is indeed difficult to style.

Have a look into Quasar's [QInput](https://quasar.dev/vue-components/input) documentation. There are props called "input-class" and "input-style". Because Quasar converts a `<q-input>` element into a hierarchy of container, input field, label and so on, applying CSS and Tailwind to the outer-most element has little to no effect. But "input-classes" and "input-style" apply to the nested `<input>` element.

I'll add a hint to the documentation, because it's probably a common pitfall.

**Comment by adarshpunj** [comment]
Thank you @falkoschindler!
