### ISSUE TITLE
Why is spawn context not supported ?

### ISSUE THREAD

**Issue by tchaton** [zauberzeug/nicegui#189]
Hey there,

I have seen ui.run doesn't support spawn.

```python
    if inspect.stack()[-2].filename.endswith('spawn.py'):
        return
```

However, after removing those lines, it seems to work just fine.

**Comment by falkoschindler** [comment]
If NiceGUI runs with auto-reload enabled, the uvicorn server spawns a new process to serve the app. When an auto-reload is triggered, this process is re-started.

The if-statement in `ui.run` prevents the spawned process from starting another server - which would not work since the port is already in use. In order to identify the process we are currently in, we inspect the stack and look for "spawn.py". Maybe there is a better way to achieve the same...

But what are you actually trying to do? Can you give some context or a minimum example?

**Comment by tchaton** [comment]
Hey @falkoschindler,

With the Lightning App Framework, we need to spawn the processes in order to move the model on GPU without CUDA Context Error.

Here is an example where I had to patch the frames in order to avoid this return checl: https://github.com/Lightning-AI/lightning-diffusion-component/blob/main/diffusion2/app_interactive.py#L61

```python
    def stack_patch():
        class FakeFrame:
            filename = "random"
        return [FakeFrame(), None]
    inspect.stack = stack_patch
    ui.run(host=host, port=port, reload=False)
```

As `reload=False`, it works just fine.

**Comment by falkoschindler** [comment]
@tchaton Would it help to replace

```python
if inspect.stack()[-2].filename.endswith('spawn.py'):
    return
```

with the following lines?

```python
if current_process().name != 'MainProcess':
    return
```

This seems to be another way to tell [if a process is parent or not](https://stackoverflow.com/a/50435263/3419103).

**Comment by falkoschindler** [comment]
@tchaton Have you had the chance to try out `if current_process().name != 'MainProcess':`? We could probably change this line pretty easily, but I'd like to know beforehand if it is any better than using `inspect.stack`.

**Comment by falkoschindler** [comment]
We think checking `current_process().name` is cleaner than inspecting the caller's stack. Therefore we changed the implementation in [e8407c0](https://github.com/zauberzeug/nicegui/commit/e8407c08ce3e046aec95221a4b7c58b40f88e9f7).
