### ISSUE TITLE
`hidden lg:block` doesn't work

### ISSUE THREAD

**Issue by adarshpunj** [zauberzeug/nicegui#1928]
### Description

I'm trying to replicate this behaviour in NiceGUI:

```html
<div class="hidden lg:block">
    Content
</div>
```

```python
ui.label("Content").classes("hidden lg:block")
```
I tried several other ways: 

- `hidden lg:flex`
- `hidden lg:visible`
- `hidden lg:block/flex/`

Is it because of clash with Quasar class [`hidden`](https://quasar.dev/style/visibility/)? 

> NiceGUI==1.4.1

**Comment by falkoschindler** [comment]
Yes, that's because "hidden" is also a Quasar class which translates to `display: none !important`. This makes it hard to override.

But you can write
```py
ui.label("Content").classes("max-lg:hidden")
```

This way Quasar doesn't apply (it doesn't know the suffix "max-lg:"), but Tailwind can set `display: none` _unless_ the "lg" breakpoint is reached.

I'll close this issue since it doesn't seem to be an problem with NiceGUI.
