### ISSUE TITLE
add ':dense="dense"' to props

### ISSUE THREAD

**Issue by v479038280** [zauberzeug/nicegui#1950]
### Description

```py
ui.input().props('standout="bg-teal text-white" v-model="text" label="Custom standout" :dense="dense" ')
```
when adding ':dense="dense"' the page in 127.0.0.1:8080 will become blank

**Comment by v479038280** [comment]
This is a example from quasar which could switch between dense and not dense
![微信截图_20231103232506](https://github.com/zauberzeug/nicegui/assets/25096045/66ff5269-858a-47dd-86cb-15641a49b9c8)
![微信截图_20231103232519](https://github.com/zauberzeug/nicegui/assets/25096045/06735008-3c14-41f7-aa99-5ef19a726015)

with :dense="dense"  we could switch between these two states?

**Comment by falkoschindler** [comment]
I see. But the example relies on a state variable "dense" on the client, which you don't have.

You can do something like this:
```py
input = ui.input().props('filled')

def handle_switch(e: events.ValueChangeEventArguments):
    if e.value:
        input.props('dense')
    else:
        input.props(remove='dense')

ui.switch('dense', on_change=handle_switch)
```

Or a bit shorter but using the private "unofficial" `_props` API:
```py
input = ui.input().props('filled')

def handle_switch(e: events.ValueChangeEventArguments):
    input._props.update(dense=e.value)
    input.update()

ui.switch('dense', on_change=handle_switch)
```

Or much shorter with a tricky one-liner for the `on_change` handler:
```py
input = ui.input().props('filled')
ui.switch('dense', on_change=lambda e: input.props('dense' if e.value else None, remove=None if e.value else 'dense'))
```

---

Anyway, because the page shouldn't stay blank just because one prop couldn't be evaluated, I added a try-catch block in commit https://github.com/zauberzeug/nicegui/commit/188629db2db52cff238ad191d47078678be92a2e.
