### ISSUE TITLE
Table object has no attribute 'view'

### ISSUE THREAD

**Issue by arolluisma** [zauberzeug/nicegui#202]
Over at stackoverflow, @Falko suggested the following code:

```python3
from nicegui import ui

table = ui.table({
    'columnDefs': [
        {'headerName': 'Task id', 'field': 'taskId'},
        {'headerName': 'Info', 'field': 'info'},
    ],
    'rowData': [
        {'taskId': 1},
    ],
})

def handle_click(sender, msg):
    print(sender)
    print(msg)

table.view.on('cellClicked', handle_click)

ui.run()
```

When I tried this, I got an `AttributeError: 'Table object has no attribute 'view'.`

So how should a click on a cell (or row for that matter) event be captured?

**Comment by falkoschindler** [comment]
Thanks for reporting this issue, @arolluisma! You're right, that's how I described how to register events on `ui.table` based on the underlying JustPy library. However, since NiceGUI 1.0 we don't use JustPy anymore. That's why there is no `view`.

But NiceGUI has now its own generic event subscription. With the newest release 1.0.7 it can be used to subscribe to table events:

```python
from nicegui import ui

table = ui.table({
    'columnDefs': [
        {'headerName': 'Task id', 'field': 'taskId'},
        {'headerName': 'Info', 'field': 'info'},
    ],
    'rowData': [
        {'taskId': 1},
    ],
})

def handle_click(msg):
    print(msg)

table.on('cellClicked', handle_click)

ui.run()
```

[Here](https://www.ag-grid.com/javascript-data-grid/grid-events/) you can find a list of events with corresponding event arguments, most of which are accessible in Python.
