### ISSUE TITLE
Upload icons not matching behaviour, upload size not updated after removing files

### ISSUE THREAD

**Issue by m-eduarda-andrade** [zauberzeug/nicegui#2021]
### Description

Creating the following upload object, with `auto_upload` True:

```py
ui.upload(
    multiple=True,
    auto_upload=True,
    on_upload=lambda e:  self.handle_upload(e),
).classes("max-w-full").style("min-height: 290px;")
```

The following icons does not match the behaviour of deleting the file:

![image](https://github.com/zauberzeug/nicegui/assets/84938840/f9d4ba51-5f4a-40a7-b4b6-b72d5eae502a)

After deleted, the upload size is not updated:

![image](https://github.com/zauberzeug/nicegui/assets/84938840/2d7d902b-d0f8-406e-8d30-474ee5e5e68c)

In the [documentation](https://nicegui.io/documentation/upload) no such problem occurs:

![image](https://github.com/zauberzeug/nicegui/assets/84938840/0a42bcd4-90a1-4e35-8bb3-40f199ca2f77)
![image](https://github.com/zauberzeug/nicegui/assets/84938840/10463383-e4ca-4bc5-803d-37b47b170c5f)

After deleting:
![image](https://github.com/zauberzeug/nicegui/assets/84938840/44dc6bfd-fdef-40d3-9889-09c0daa90175)

**Comment by falkoschindler** [comment]
You're using `auto_upload=True`. Therefore the files are uploaded immediately, thus cannot be deleted which is indicated by the checkmark instead of a delete icon. And since they are already uploaded, the size is not updated. The NiceGUI documentation doesn't use auto upload, explaining the difference you observe.

I'd argue this is the normal behavior of Quasar's [QUploader](https://quasar.dev/vue-components/uploader) component and there's not much we can do about it.

**Comment by m-eduarda-andrade** [comment]
> You're using `auto_upload=True`. Therefore the files are uploaded immediately, thus cannot be deleted which is indicated by the checkmark instead of a delete icon. And since they are already uploaded, the size is not updated. The NiceGUI documentation doesn't use auto upload, explaining the difference you observe.
> 
> I'd argue this is the normal behavior of Quasar's [QUploader](https://quasar.dev/vue-components/uploader) component and there's not much we can do about it.

Thank  you!
