### ISSUE TITLE
Favicon does not get displayed at root page.

### ISSUE THREAD

**Issue by JS-Aibel** [zauberzeug/nicegui#240]
The following code is showing default favicon on the root page “/”. 
The page “other_page” shows the correct favicon.

```
@ui.page('/', favicon=os.path.join("icon.png"))
def rootPage():
    ui.link('Visit other page', other_page)

@ui.page('/other_page', favicon=os.path.join("icon.png"))
def other_page():
    ui.label('Welcome to the other side')
```

**Comment by falkoschindler** [comment]
Oh, thanks for reporting this bug! The favicon is indeed wrong on the index page. I'll look into it.

**Comment by falkoschindler** [comment]
Ok, it turned out to be an easy fix: The page at "/" correctly created the new favicon route. But there was already a route with the same path from the [auto-index page](https://nicegui.io/reference#auto-index_page), which happened to get used for serving the icon. With commit [6f81dd7](https://github.com/zauberzeug/nicegui/commit/6f81dd7244699b72dc11c27d7a8d6e37505c6c22) we make sure to remove duplicate routes before adding a new one. This should resolve this issue.

**Comment by IvanKachuraAsist** [comment]
Cleaned cash. Everything works.
Thank you for this project.
