### ISSUE TITLE
number input only accept one integer value and auto add  decimal point ?

### ISSUE THREAD

**Issue by jekoie** [zauberzeug/nicegui#2454]
### Description

I define a number input, when user delete all digit and input an empty value, it will show "None Value" error.But when I input
a number, `number` input  add a  decimal point when I input first integer. 

```python
from nicegui import app, ui
ui.number("xx", min=1, max=9999, precision=3, validation={"None Value": lambda v: v!=None})
ui.run()

```

**Comment by falkoschindler** [comment]
Hi @jekoie, thanks for reporting this issue!

To clarify:

```py
ui.number(validation={'No value': lambda v: v is not None})
```

1. Type "1".
2. Clear number input. The error "No value" appears.
3. Type "1" again. The input value changes to "1,0", but should remain "1".

I think the problem is that the changing error state triggers an update, which sets the input value and breaks the user interaction. Not sure how to fix that. 😕

**Comment by falkoschindler** [comment]
Ok, I think we fix it with a tiny extra condition:
https://github.com/zauberzeug/nicegui/blob/8d91ca36177bff30a22b3e9526128b8c50b75647/nicegui/elements/number.py#L122-L124

If the value _was_ an integer and the new value is _still_ an integer, we return an integer representation.

**Comment by jekoie** [comment]
Thanks, I will try later.
