### ISSUE TITLE
Add PWA support

### ISSUE THREAD

**Issue by schmurian** [zauberzeug/nicegui#246]
Since NiceGUI is both mobile-friendly and allows to be hosted as a webapp, it would be great if PWA (Progressive Web App) support would be added to the library. This way it would be possible to "install" the app on desktops and mobile devices.

As an example implementation see:

https://github.com/umluizlima/flask-pwa

(This is build around Flask, but I think it should give an idea of what I have in mind)

**Comment by rodja** [comment]
In my understanding we would just need tow things:

1. launch the website in a native window (see https://github.com/zauberzeug/nicegui/discussions/89).
2. test/describe packaging with cx_Freeze, PyInstaller, py2exe, PyOxidizer or similar

Flask-pwa needs to do much more because flask does not have frontend mechanisms by itself. Do you agree @schmurian?

**Comment by schmurian** [comment]
Your solution is valid for desktop apps, but my request would add the same "native" experience for smartphones.

And it is not too much that is added for webapps to be installable, when following the guidelines from flask-pwa.

**Comment by rodja** [comment]
Hmm... I fear NiceGUI would not be the right technology for what you have in mind @schmurian. Our architecture relies on a running Python backend which executes the business logic and just renders the result into the web browser. For PWA as I understand it, everything (including all business logic) needs to be done in JavaScript.
NiceGUI allows to embed arbitrary JS, so you could create a PWA with it. But you won't be able to use the ui elements and such.

**Comment by schmurian** [comment]
Got it. Will try to add the files myself.
I really like how easy it is to build an app which niceGUI which is why I'd like to combine both.

Thank you for looking into it!

**Comment by rodja** [comment]
Sure. Feel free to share any success stories in https://github.com/zauberzeug/nicegui/discussions/categories/show-and-tell. We are eager to see what you come up with.

**Comment by schmurian** [comment]
Happy to share, in case I get it to work.

**Comment by Shahin-rmz** [comment]
I second this.
in other words, there are some Qasar components which are not mobile friendly.
I mean Date and time input.

**Comment by PeterMarkuson** [comment]
You can achieve the "pwa" look with that neat install button by providing a manifest file and a service_worker.js. If a user visits your page, he will see a notification to install the app. And of cause you can use the APIs from the browser (like notifications) to make your app look even more native.

However, this will not lead to a pure offline experience, because the backend needs to be there. But it leads to a nice setup for new users.

Here is what I have achieved so far:
This is manifest.json. Please replace the values in capital to your liking
~~~
{
    "name": "APP_NAME",
    "short_name": "APP_NAME",
    "theme_color": "#2196f3",
    "background_color": "#2196f3",
    "display": "standalone",
    "orientation": "portrait",
    "scope": "/",
    "start_url": "/home",
    "id": "YOUR_UNIQUE_APP_ID",
    "display_override": [],
    "icons": [
        {
            "src": "icon-192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "icon-512.png",
            "sizes": "512x512",
            "type": "image/png"
        }
    ]
}
~~~

This is an optimized service-worker who caches static files (e.g. media), but does nothing on web-socket-connections:
~~~
const CACHE_NAME = 'APP_NAME-vYOUR_VERSION_NUMER';
const CACHE_URLS = [
    '/media/'
];

// WebSocket connections to be excluded from the fetch handler
const WEBSOCKET_URLS = [
    'wss://',
    'ws://'
];

self.addEventListener('install', (event) => {
    event.waitUntil(
        caches.open(CACHE_NAME).then((cache) => {

            return Promise.all(
                CACHE_URLS.map(url => {
                    return cache.add(url).catch(error => {
                        console.error('Failed to cache:', url, error);
                    });
                })
            );
        })
    );
});

self.addEventListener('fetch', (event) => {
    // Check if the request is for a WebSocket
    if (WEBSOCKET_URLS.some(wsUrl => event.request.url.startsWith(wsUrl))) {
        // Don't interfere with WebSocket connections
        return;
    }

    event.respondWith(
        caches.match(event.request).then((response) => {
            return response || fetch(event.request);
        })
    );
});

self.addEventListener('activate', (event) => {
    const cacheWhitelist = [CACHE_NAME];
    event.waitUntil(
        caches.keys().then((cacheNames) => {
            return Promise.all(
                cacheNames.map((cacheName) => {
                    if (cacheWhitelist.indexOf(cacheName) === -1) {
                        return caches.delete(cacheName);
                    }
                })
            );
        })
    );
});

// Handle WebSocket keep-alive
self.addEventListener('message', (event) => {
    if (event.data === 'keepalive') {
        // Respond to keep-alive messages
        event.ports[0].postMessage('alive');
    }
});
~~~

You need to bind these to files with the `app.add_static_file` command to your "/" URL (or wherever the install option should appear).

I am not a professional programmer and have only minor knowledge in JavaScript. If anybody has come up with a better solution or can improve my approach, I would be happy to see that :)

BR/Peter

**Comment by rodja** [comment]
Some additional infos / discussion about PWA can be found in #3810.
