### ISSUE TITLE
Consider relaxing the upper bounds on some requirements

### ISSUE THREAD

**Issue by sscherfke** [zauberzeug/nicegui#2485]
### Description

Many requirements of nicegui have upper bounds.  I understand the principal need for this, but upper bounds can make repackaging harder or using nicegui in larger environments tricky.

For example, setuptools is pinned to <50, but Nicegui works just fine with recent versions.  Aiofiles is pinned to < 24.0.0 but this makes not sense with cal-ver, because the first release of this year is not necessarily more likely to introduce breaking changes than the last release of 23.*.

And, out of curiosity, why did you re-add aiohttp as requirement?  It seems nowhere to be used.  The links to the "dependabot issues" in the corresponding commit don't work.

**Comment by falkoschindler** [comment]
Thanks a lot for these suggestions, @sscherfke! Let me share my thoughts:

- We try to relax requirements where possible, but also had some bad experiences with loose upper bounds (looking at you, FastAPI). Nevertheless, it's good to re-evaluate the requirements regularly.
- I'm not sure why we introduced setuptools<50 two years back. We can probably remove the upper bound.
- Regarding aiofiles: I wasn't aware of cal-ver and that aiofiles is using it. It totally makes sense to remove the upper bound - at least if we don't restrict the minor version.
- aiohttp is used by python-engineio and had a security issue in <3.9.2. The dependabot page is probably private, which is why you can't access it. Here is the corresponding CVE: https://nvd.nist.gov/vuln/detail/CVE-2024-23829.

Would you like to create a pull request relaxing the mentioned (and maybe more) dependencies? 🙂

**Comment by sscherfke** [comment]
Thanks for the quick reply :-)

I’ll open a PR in the next few days.

**Comment by sohnemann** [comment]
Hi everyone :)

I'm trying to add nicegui to a Yocto image I'm building.

The issue that I'm facing is that the **setuptools** version included in the scarthgap branch is **69.1.1**,
yet nicegui requires ```setuptools <50```.

Could someone please have a look?
Any help with this is much appreciated.

**Comment by rodja** [comment]
@sohnemann I do not see any enforcement of setuptools in our [pyroject.toml](https://github.com/zauberzeug/nicegui/blob/main/pyproject.toml). If the problem persists I suggest you create a new discussion and post the error you are seeing.

**Comment by sohnemann** [comment]
@rodja It's on line 84:

`[build-system]
requires = [
    "setuptools>=30.3.0,<50",
    "poetry-core>=1.0.0"
]
build-backend = "poetry.core.masonry.api"`

**Comment by rodja** [comment]
You are right. Sorry. I do not think there is any reason to have `< 50`. I just created https://github.com/zauberzeug/nicegui/pull/4033 to remove this in the next release.

**Comment by sohnemann** [comment]
Awesome, thank you! :)
