### ISSUE TITLE
tooltip method does not use ui.tooltip.default_classes() settings

### ISSUE THREAD

**Issue by h0uter** [zauberzeug/nicegui#2554]
### Description

1. I tried to make all my tooltips bigger that I coded using the method syntax. 
2. I expected the tooltips resulting from the tooltip method to also use the default_classes and get bigger.
3. They stayed the same size

## Minimal reproducible example
```py
from nicegui import ui

ui.tooltip.default_classes("text-h3")

with ui.button("working"):
    ui.tooltip("I get the default class")

ui.button("not working").tooltip("I dont get the default class.")
ui.run()
```

**Comment by falkoschindler** [comment]
Thanks for reporting this bug, @h0uter!

I just looked into the code and the mistake is pretty obvious: In order to avoid cyclic imports, the `.tooltip()` method uses a generic `Element('q-tooltip')` instead of a `ui.tooltip`. But this ignores default classes assigned to `ui.tooltip`.

We somehow need to find a way to use the `Tooltip` class without introducing a cyclic dependency. 🤔
