### ISSUE TITLE
404 error page not rendered on static file routes

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#2570]
### Description

As noticed by @Anindya088 (#2568), the 404 error page isn't rendered correctly when accessed via a (sub-)path of a static route. Take this code for example:

```py
app.add_static_files('/static', '.')
ui.link('Static', '/static')
```

When visiting `/static` or `/static/subpage`, the HTML page is displayed, but without any CSS and JS assets. They are requested from a wrong path and, thus, not used for rendering the page.

**Comment by rodja** [comment]
Thanks for the PR, @Lucas-lyh. It made me dig a bit deeper into the issue. I think the problem was introduced with #848 which sets the path prefix to `scope['root_path']` -- which is correct in my opinion:

https://github.com/zauberzeug/nicegui/blob/cc7770e210b415409131cc83128d649ed838a7a0/nicegui/client.py#L116

But, `app.add_static_files` uses `app.mount` internally:

https://github.com/zauberzeug/nicegui/blob/cc7770e210b415409131cc83128d649ed838a7a0/nicegui/app/app.py#L156

This is defined in the ASGI standard to alter the `scope['root_path']` -- which is not desired in this case. Because there is no  way to tell the FastAPI/Starlette (which implements ASGI) to not alter `scope['root_path']`, we may be forced to implement `app.add_static_files` in some other way :-(
