### ISSUE TITLE
Unable to set `ui.select` value to multiple values 

### ISSUE THREAD

**Issue by amks1** [zauberzeug/nicegui#2682]
### Description

```python3
from nicegui import ui

flag = 0     # to toggle between options

def update_options():
    global flag
    if flag == 0:
        sel.options = ['a', 'b', 'c']
        sel.value = ['a', 'b', 'c']
        flag = 1
    else:
        sel.options = []
        sel.value = None
        flag = 0
    sel.update()
    
sel = ui.select(options=[], multiple=True).style('width: 200px')
ui.button('Update Options', on_click=update_options)
ui.run()
```

The selected values are not set programmatically on clicking the button. Selection don't get set from `None` to `['a', 'b', 'c']` when the button is first clicked. The same issue is observed if I change the code to use the builtin function:

```python3
sel.set_options(options=['a', 'b', 'c'], value=['a', 'b', 'c'])
```

**Comment by falkoschindler** [comment]
Hi @amks1, thanks for reporting this issue!

There are actually two aspects:

1. After changing `sel.options`, you should call `sel.update()`. Only then you can change `sel.value` (another `ui.update` is not needed). Otherwise the frontend doesn't accept the new value, because the new options haven't been synchronized.

2. The method `set_options` should do that automatically. I improved it accordingly in https://github.com/zauberzeug/nicegui/commit/25e0695257519812a7d88b6a805315021bfa36df, so it should work as expected in the next version.
