### ISSUE TITLE
Autopep8 enforces the maximum line length differently

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#2750]
### Description

As noticed by @petergaultney in https://github.com/zauberzeug/nicegui/pull/2704#issuecomment-2000575550, the CONTRIBUTING.md file recommends running

```bash
autopep8 --max-line-length=120 --experimental  --in-place --recursive .
```

to auto-format the code, which causes quite some changes in the codebase, which is usually formatted with the [autopep8 VSCode extension](https://marketplace.visualstudio.com/items?itemName=ms-python.autopep8). There are 15 files with too long lines that get wrapped. I tried removing the `--experimental` argument, which doesn't seem to make a difference.

- [ ] Somehow we need to find a configuration that yields the same results via VSCode or the command line.
- [ ] By the way, I wonder what `--experimental` is supposed to do. Maybe we can remove it.
- [ ] And while at it, we should fix these 15 files, which violate the maximum line length.

**Comment by petergaultney** [comment]
one minor add-on question here: would y'all consider introducing something like [`pre-commit`](https://pre-commit.com/) so that at least a few of these things can be set up as git commit hooks for developers? It's not something that can get _enforced_ locally, but it does make it a little easier for devs not to miss running them.

**Comment by falkoschindler** [comment]
@petergaultney Yes, there have been attempts towards pre-commit hooks recently (PR https://github.com/zauberzeug/nicegui/pull/2563 and PR https://github.com/zauberzeug/nicegui/pull/2619) and we're definitely considering it. But I guess we need to find a "recipe" first, which works on all machines and yields same results like the IDE integration(s) we're recommending to use.

**Comment by codingpaula** [comment]
When I run the autopep8 command without the `--experimental` flag, it doesn't change these 15 files for me. And since the changes for the long lines in these cases are in some cases a little weird, the easiest option would be to remove the `--experimental` from the suggested command. Then VSCode and the command yield the same result.
