### ISSUE TITLE
Updating interactive_image content is much slower when coming from a bound variable

### ISSUE THREAD

**Issue by e-dorigatti** [zauberzeug/nicegui#2797]
### Description

Hello, I would like to quickly refresh the content of an interactive_image, ideally changing something at every mouse movement. I could achieve this by directly modifying the image content, but when I try to bind the content of the image to a variable, the UI updates are noticeably slower:

```python
from nicegui import ui

class Example:
    def __init__(self):
        self.content = ""
        self.image = ui.interactive_image(
            size=(400, 400), on_mouse=self.mouse_event, events=["mousemove"]
        ).style("border: 1px solid black; width: 400px; height: 400px;")
        self.image.bind_content(self, "content")

    def mouse_event(self, e):
        ui.notify("mouse event")
        x, y = e.image_x, e.image_y
        cont = f'<circ cx="{x}" cy="{y}" r="50" />'

        # self.image.content = cont  # this is fast
        self.content = cont  # this lags ...


viewer = Example()
ui.run()
```

What I see on the browser profiler is that for the slow version Vue seems not to update the image at every frame, but only once every 5 or 10. This function is highlighted below, followed by two frames in which it was not called:

![](https://media.discordapp.net/attachments/1224326508206886949/1224359700330709012/image.png?ex=661d34d4&is=660abfd4&hm=a40206fc6e0897916b51a4272a9c59a20862c6ee87b65714219f5a24c7e21518&=&format=webp&quality=lossless&width=550&height=591)

**Comment by falkoschindler** [comment]
Hi @e-dorigatti,

This is caused by the way binding works in NiceGUI. In your example, NiceGUI checks the value of `self.content` regularly to see if it has changed. So the refresh rate depends on the `binding_refresh_interval`. It's a `ui.run` parameter and defaults to 0.1s. You can adjust this interval, but it might increase the overall CPU load.

Alternatively you can make `self.content` a "bindable property":
```py
from nicegui import binding, ui

class Example:
    content = binding.BindableProperty()

    def __init__(self):
        ...
```
This allows NiceGUI to observe any access to this field, so that it can update bound objects directly without the need for regular checking the value in a loop. This way your example runs smoothly and resource-efficient.

See [this ](https://github.com/zauberzeug/nicegui/discussions/1975#discussioncomment-7514899) for a related explanation.

**Comment by e-dorigatti** [comment]
Hi @falkoschindler, thanks a lot for the explanation and sorry for opening a non-issue! I started using NiceGUI last week and really loving it :)
