### ISSUE TITLE
Windows Testing Mayhem

### ISSUE THREAD

**Issue by afullerx** [zauberzeug/nicegui#2854]
### Description

I'm working on a pull request and I've been locked in mortal combat with the automated test suite for a couple days. Whether I run it with my changes or the original code, I get lots of errors. The fun part is most of them are different every time. I can't get the same result twice. Some will fail when I run them all together, but then pass when I run them individually. It'll tell me it can't find "42" on the page, but when I check the screenshot, it's there. Except sometimes it's not. My personal favorite is: `selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: -0.000` "-0.00"?????😂 There are a ton of those spewed randomly through the results, but they never occur when running the tests individually. Most of the issues seems to be general Selenium flakiness, but all the solutions I found online recommend settings that are already present. So, I quickly abandoned that.

I'm hoping this is all just because I'm running them on Windows. I'm planning on trying to get them running on Linux in Docker, but before I spend any more time, I just wanted to see if I could get verification from anyone with experience: If I use the dev container, are the tests expected to run cleanly against the current code base? (Or at least deterministically?) I probably should have done this to start with, but I figured I'd use Windows as that's where I had the original issue that led me down this rabbit hole.

**Comment by falkoschindler** [comment]
Hi @afullerx, I'm sorry to hear that you're struggling so badly with our pytests.

At the moment we're quite happy with them, because we seem to have solved all flakyness when running them locally on MacOS or on GitHub actions. But I can very well imagine that there are more issues, especially on Windows.

Does anyone experience similar problems when testing on Windows? Does anyone have an idea what to do about it?

Using a Docker container is probably a good workaround. If the tests run cleanly in isolation, I'd expect them to pass when run on GitHub. I'll leave this issue open so that we can discuss and improve it with the community. But I don't think you should spent too much time fighting the test infrastructure.

**Comment by afullerx** [comment]
@falkoschindler Thanks for the response. I'm glad to hear they're working reliably on Mac and Docker. I guess there's a reason so few developers seem to be using Windows these days. I'll go the Docker route. I don't mind investing the time as I want to get an efficient workflow going so that I can contribute more easily in the future.

**Comment by afullerx** [comment]
The solution here is definitely to use the Docker dev container. Following the instructions in `CONTRIBUTING.md`, I was able to get it up and running in minutes. As compared to running them natively on Windows, the tests ran in 1/4 the time, gave informative progress output, and most importantly yielded reproducible, highly useful results. This also will ensure compatibility with Python 3.8. Note: The "Remote-Containers" extension mentioned has been renamed to "Dev Containers".

**Comment by falkoschindler** [comment]
Since the problem has been solved using the provided dev container, I'll close this issue.
