### ISSUE TITLE
Font missing in NiceGui 1.0

### ISSUE THREAD

**Issue by JS-Aibel** [zauberzeug/nicegui#295]
`style('font-weight: 1000')` gives the error: `http://127.0.0.1:8080/_nicegui/static/fonts/KFOlCnqEu92Fr1MmYUtfBBc4AMP6lQ.woff2 not found` in NiceGui version 1.0. The style works without errors in version 0.9.

Example code:
`ui.label('Test').style('font-weight: 1000')`

**Comment by falkoschindler** [comment]
Oh, wow! Thanks for reporting this bug!

It looks like font "KFOlCnqEu92Fr1MmYUtfBBc4AMP6lQ" is the only one with file extension "woff" instead of "woff2" - for whatever reason:

https://github.com/zauberzeug/nicegui/tree/3fc20cbc47a801a3b7b5e9d646a507990065e62b/nicegui/static/fonts

I'll check if we should rename the file or change the URL in fonts.css.

**Comment by falkoschindler** [comment]
Ok, it's fixed in [f99ab75](https://github.com/zauberzeug/nicegui/commit/f99ab750d754161c2e23166055730ad0b2ecc705). The woff file didn't even contain the font but an error message from Google. I downloaded the file again and now everything works as expected.
