### ISSUE TITLE
2-way bindings backward direction does not work anymore

### ISSUE THREAD

**Issue by rodja** [zauberzeug/nicegui#3044]
### Description

Originally brought up by [petewallis46_29624 on Discord](https://discord.com/channels/1089836369431498784/1235579777096745031),  it seems that the backward propagation stopped working in one of the recent NiceGUI releases. Here is a reproduction:

```py
data = {'A': 1}
input = ui.number().bind_value(data, "A")
ui.label(f'data: {data["A"]} input: {input.value} -> initial values match')

input.set_value(2)
ui.label(f'data: {data["A"]} input: {input.value} -> forward binding values match')

data['A'] = 3
ui.label(f'data: {data["A"]} input: {input.value} -> backwards binding values do not match'). \
    classes('text-red-500')

input.set_value(4)
ui.label(f'data: {data["A"]} input: {input.value} -> forward binding values match again')
```

The result is

```
data: 1 input: 1 -> initial values match
data: 2 input: 2 -> forward binding values match
data: 3 input: 2 -> backwards binding values do not match
data: 4 input: 4 -> forward binding values match again
```

**Comment by falkoschindler** [comment]
I think the backward binding is working. Here is an example where button clicks trigger the value changes:
```py
data = {'A': 1}
input = ui.number().bind_value(data, "A")
ui.label().bind_text_from(data, 'A')
ui.label().bind_text_from(input, 'value')

ui.button('Input := 2', on_click=lambda: input.set_value(2))
ui.button('Data := 3', on_click=lambda: data.update(A=3))
ui.button('Input := 4', on_click=lambda: input.set_value(4))
```

The problem with the original code is probably a timing issue: After setting the data value to 3, the binding needs some time to propagate its value. But the label is added synchronously, so the binding loop didn't get a chance to do that yet and the input value is still 2. When setting the input value to 4, the value is propagated immediately (because the `value` is a BindableProperty) and both values are 4.
