### ISSUE TITLE
local_file_picker Example error in version 1.4.25:

### ISSUE THREAD

**Issue by epmb1n** [zauberzeug/nicegui#3072]
### Description

raise RuntimeError('Cannot await JavaScript responses on the auto-index page. '
RuntimeError: Cannot await JavaScript responses on the auto-index page. There could be multiple clients connected and it is not clear which one 
to wait for.

**Comment by mattloose** [comment]
Hi - yes I've seen this too since the update from 1.4.24 to 1.4.25.

Conceptually it seems like the correct thing however - I had previously observed that if using the file picker with multiple connections on the auto-index page it caused a problem. I'd love to know what a work around is for the demo to see if I can apply it to my own code!

**Comment by falkoschindler** [comment]
Thanks for reporting this issue, @epmb1n! I fixed it by moving the local file picker into a `@page` function.

**Comment by epmb1n** [comment]
> Thanks for reporting this issue, @epmb1n! I fixed it by moving the local file picker into a `@page` function.

Hello bro, can you write an example that one of the AGGRID columns is a button,like as the example -editable_table,When in the py file, I don't know how to set the value of "cellRenderer" to a JSclass

**Comment by jweite-amazon** [comment]
I'm getting this on example _editable_ag_grid_ too.  I didn't have success moving its components into an @page func myself.

**Comment by falkoschindler** [comment]
@jweite-amazon Thanks, I fixed it in 2d69785c3654fcebd7947d873bc286eba59ab374.
