### ISSUE TITLE
container.clear silently deletes timers created in event handlers

### ISSUE THREAD

**Issue by adosikas** [zauberzeug/nicegui#3187]
### Description

I ran into this when having a "refresh" button which started a timer inside a `ui.refreshable`, and have narrowed it down to this minimal example:

```python
from nicegui import ui

def do_stuff_delete_self(e):
	ui.timer(0.5, lambda: ui.notify("This lambda runs"), once=True)
	e.sender.delete()

def do_stuff_clear_container(e):
	ui.timer(0.5, lambda: ui.notify("This lambda never runs") once=True)
        container = e.sender.parent_slot.parent
	container.clear()  # this also marks the timer as deleted, so it doesn't run once the interval is complete

ui.button("Delete Button", on_click=do_stuff_delete_self)
with ui.element():
	ui.button("Clear Container", on_click=do_stuff_clear_container)
	
ui.run()
```

I would have expected timers to start a background task, and expected both to work. (Or both not to work)
However, right now clearing the parent container deletes the timer, while deleting the button doesn't.

This is because of the `with parent_slot:` in `events.handle_event`, so the timer is a child of the container (instead of e.g. the button).

I am not sure why `with parent_slot:` is used there (instead of `with arguments.sender`), so not sure if this is fixable.

One solution could be the option to "detach" timers from their elements (so they run even when the element is deleted) but not sure how much that would break.

**Comment by falkoschindler** [comment]
Hi @adosikas,

Timers are designed to behave like UI elements, such that once they are removed from the page, they are no longer active. The other concept to keep in mind is that new elements are always placed in the current context. In case of a button click this is the button's parent slot. So if you create a timer inside a click handler and clear the parent container afterwards, the timer never runs. You can move the line with `ui.timer` further down so that it gets added as a new element to the cleared container. Or you create the timer somewhere further up in the DOM, e.g. in the client's `page` or `layout` element:
```py
with ui.context.client.layout:
    ui.timer(0.5, lambda: ui.notify("This lambda never runs"), once=True)
```

We'll have to think about how we can avoid this confusion. A `detach` parameter might be an option.

**Comment by falkoschindler** [comment]
I created feature request #3225 to discuss a non-ui `app.timer`.
