### ISSUE TITLE
Dark mode switch `ui.expansion()` color to white

### ISSUE THREAD

**Issue by podzit** [zauberzeug/nicegui#3232]
### Description

with `ui.run(dark=True)` any color on `ui.expansion().classes()` or `ui.expansion().style()` is switched to white.
workaround : 
- remove `dark=True` in `ui.run()`
- add `ui.query('body').classes('bg-black')` at the top of the main script.

**Comment by falkoschindler** [comment]
Hi @podzit,

I think the reason for the white text color in dark mode is that you actually should use the "header-class" or "header-style" prop to style the expansion header:
```py
with ui.expansion('This is blue', value=True).classes('text-red-500').props('header-class=text-blue-500'):
    ui.label('This is red')
```
This works with light and dark mode.

The behavior of `.classes()` and `.style()` is pretty confusing, since it works in light mode. But I guess this due to the interaction of Quasar, Vue and CSS, and we can't do much about it.
