### ISSUE TITLE
Lift fastapi dependency to 0.112

### ISSUE THREAD

**Issue by aersam** [zauberzeug/nicegui#3622]
### Description

I think you should not restrict fastapi at all, or maybe to <1.0 or so. Breaking changes are very rare

I can also do a PR

**Comment by python-and-fiction** [comment]
It is ready in 2.0
https://github.com/zauberzeug/nicegui/pull/3604

**Comment by falkoschindler** [comment]
See #2755 for an explanation of why we limited FastAPI to 0.109.0.

**Comment by aersam** [comment]
I think if you really rely on this edge case in fastapi, you could also pin 0.109 and nicegui could declare >=0.109 which would allow me to use 0.112 🙃

**Comment by falkoschindler** [comment]
You're right, #2755 is not the best example, because the breaking change in 0.110.0 doesn't really affect us.
But #2354 was indeed a bug caused by FastAPI changing some crucial code in 0.109.0 how ASGI apps are mounted.

Anyway, given your input and many other requests for opening the upper bound for the FastAPI version, we're considering switching to `>=0.109.1` in NiceGUI 2.0, which is due in a few days. We will guard ourselves with hourly dependabot checks to catch breaking releases as fast as possible.
