### ISSUE TITLE
Sticky page children full width not working

### ISSUE THREAD

**Issue by h0uter** [zauberzeug/nicegui#3671]
### Description

1. What: trying to make a child of `sticky_page` full width
2. Expectations: Setting `.classess("w-full")` on the child element makes it full width
3. Instead: The width doesn't change

minimal example

```py
from nicegui import ui

with ui.page_sticky("right", x_offset=10, y_offset=10).classes("w-1/3 bg-blue-100"):
    ui.card().classes("w-full h-full")
    ui.card().classes("w-full")

    ui.card().props("full-width")

ui.run()
```
<img width="934" alt="Screenshot 2024-09-03 at 21 51 25" src="https://github.com/user-attachments/assets/f84d225d-c05c-41ce-8d10-084f48595779">

**Comment by falkoschindler** [comment]
Hi @h0uter,

This is a confusing behavior, I have to commit. But it looks like it is caused by Quasar's QPageSticky component, which wraps the cards in another `<div>` so that the card's "w-full" doesn't expand to the sticky element's width.

But there's a prop ["expand"](https://quasar.dev/layout/page-sticky) for changing this behavior:
```py
with ui.page_sticky("right", x_offset=10, y_offset=10).classes("w-1/3 bg-blue-100").props("expand"):
    ui.card().classes("w-full")
```
<img width="495" alt="Screenshot 2024-09-04 at 07 26 45" src="https://github.com/user-attachments/assets/eb28900a-d43f-4519-9a32-ee9c7fed4124">

**Comment by falkoschindler** [comment]
I decided to add an `expand` parameter to `ui.page_sticky` to make this feature more discoverable.
