### ISSUE TITLE
Disabling tailwind leads to JavaScript runtime error

### ISSUE THREAD

**Issue by rbeeli** [zauberzeug/nicegui#369]
There seems to be an error when setting `ui.run(tailwind=False)`:

**templates/index.html**

```
      const dark = False;
      Quasar.Dark.set(dark === None ? "auto" : dark);
      if (dark !== None) tailwind.config.darkMode = "class";
```

_tailwind_ is undefined, hence JavaScript runtime error.

See here: [https://github.com/zauberzeug/nicegui/blob/e155c80da5145f4a3cf20ce5945958be35f4c80f/nicegui/templates/index.html#L150](https://github.com/zauberzeug/nicegui/blob/e155c80da5145f4a3cf20ce5945958be35f4c80f/nicegui/templates/index.html#L150)

Sidenote: IMO would remove Tailwind completely and leave integration if wanted to the user. Quasar has plenty CSS functionality. I think most users won't benefit from Tailwind much anyways.

**Comment by falkoschindler** [comment]
Thanks, @rbeeli, for reporting this bug!
It should be fixed with [5b5800c](https://github.com/zauberzeug/nicegui/commit/5b5800c71d4c8e08aec4826c06654a017a5073f1).

Whether or not to include Tailwind in NiceGUI is probably out of scope of this issue and might be worth a [discussion](https://github.com/zauberzeug/nicegui/discussions).
