### ISSUE TITLE
The .bg-primary class is messing with Tailwind's Background Color styling system on Buttons

### ISSUE THREAD

**Issue by Diegiwg** [zauberzeug/nicegui#371]
Referenced class:

```css
.bg-primary {
    background: var(--q-primary) !important;
}
```

When we remove the `!important`, all the buttons turn white.

I tried
```python
styles.Backgrounds(ui.button("Test")).background_color("bg-red-800")
```
and it didn't work. It continued with the normal NiceGUI color.

Then, when I disabled the style of the class in the developer tool, it worked.

---

Task list:

- [x] add a parameter `ui.button(..., color: Optional[str] = 'primary')`
    - [x] handle `None`
    - [x] handle Quasar color palette
    - [x] handle CSS color
    - [x] handle Tailwind colors?
- [x] same for `ui.avatar` and other elements
- [x] tests
- [x] documentation

**Comment by falkoschindler** [comment]
Thanks for reaching out, @Diegiwg!
Your description is a bit vague, but I guess I understand what you're saying:
You're referring to Quasar's CSS definition of `.bg-primary` which is used by `ui.button`. And `background_color` basically sets the Tailwind class "bg-red-800". Since Quasar defines its background color as `important`, it's not easy to overwrite it with a Tailwind color. That's the downside of combining two UI frameworks with overlapping style definitions.

But I'm not sure what to do about it. `ui.button`, which is based on [QBtn](https://quasar.dev/vue-components/button), creates a rather complex HTML element with various styling classes. I doubt we can avoid clashes with Tailwind in such cases.

**Comment by Diegiwg** [comment]
I tried using classes(remove="bg-primary") on the button, but it didn't work.

The class continues to exist in the button. I also don't know how to solve this problem, other than applying the style manually with !important.

**Comment by falkoschindler** [comment]
I'll close this issue. We don't see any (easy) way to avoid these kind of conflicts between Quasar and TailwindCSS.

**Comment by miqsoft** [comment]
Hey,

I used the following solution for the problem and it solved it.

``` python      
btn = ui.button('CustomButton')
del btn._props['color']
btn.classes('bg-slate-300')
```

It's still not optimal since we need to modify the internal _props dictionary.
An option would be to implement a method to the button class that removes color from props.

**Comment by rodja** [comment]
@Diegiwg we want track the idea @falkoschindler described https://github.com/zauberzeug/nicegui/issues/371#issuecomment-1494242035 on this card to make it more simple for users to actually change the background color of buttons (and other elements).

**Comment by miqsoft** [comment]
I like the proposed solution!

I figured out that the same "problem" with the background color occurs also when using the avatar in code like the following:

```python

avatar = ui.avatar('account_circle', font_size="4rem", size="4rem").classes('text-slate-200 bg-cyan-900')

```

As fas as I understood it, it's the same issue.

**Comment by falkoschindler** [comment]
Good catch, @miqsoft! We should address it as well.

**Comment by falkoschindler** [comment]
@rodja Would you like to review? (It got a bit larger than anticipated. Otherwise I would have created a PR for easier review.)
I moved the color logic into a separate module. One could argue that it should live directly in element.py. But that module is already pretty big and `set_text_color` and `set_background_color` are not meant to be public API (yet) anyway.

**Comment by rodja** [comment]
Looks great!

**Comment by stefan-sherwood** [comment]
I realize this issue is Closed but it's worth noting that there this solution doesn't work for changing the background color of a button after construction. Because `colors.set_background_color()` only adds attributes and the Quasar color css uses `!important`, it is necessary to remove the old properties and add new ones. For example:

```
from nicegui import ui

def change_button_color_works():
  b1.props( 'color=positive' )

def change_button_color_doesnt_work():
  b2.style( 'background-color: blue' )

def change_button_color_works_2():
  b3.props( remove='color' )
  b3.style( 'background-color: rgb(100 100 255)' )

b1 = ui.button( 'click to change color', color='negative', on_click=change_button_color_works )
b2 = ui.button( 'click to change color', color='negative', on_click=change_button_color_doesnt_work )
b3 = ui.button( 'click to change color', color='negative', on_click=change_button_color_works_2 )

ui.run()
```

It's also worth noting a weird quirk of the code such that if after changing the color of b3 you try this:

```b3.style( remove='background-color' )```

you get an error

```
not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "C:\Apps\Python\Lib\site-packages\nicegui\events.py", line 281, in handle_event
    result = handler() if no_arguments else handler(arguments)
             ^^^^^^^^^
  File "C:\Code\test.py", line 12, in change_button_color_works_2
    b3.style( remove='background-color' )
  File "C:\Apps\Python\Lib\site-packages\nicegui\element.py", line 144, in style
    for key in self._parse_style(remove):
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Apps\Python\Lib\site-packages\nicegui\element.py", line 130, in _parse_style
    key, value = word.split(':', 1)
    ^^^^^^^^^^
```

which can be remedied by using the peculiar code (note trailing colon)

```b3.style( remove='background-color:' )```

If anyone thinks I should file one or more bugs on these issues, LMK. It took me some puzzling to get to this point so hopefully this will help someone, especially since examples in either the documentation or sample code that set colors using RGB values are scarce and difficult to find.

**Comment by falkoschindler** [comment]
@stefan-sherwood Thanks for bringing this up! Changing the color is indeed a bit unpredictable. We thought about it and came up with an idea: Implementing the color property as mixin (like TextElement, ContentElement etc.) would move the color logic into a separate class and would allow adding getters, setters and binding. I'll create a PR and add a link to it here.

**Comment by adityapant1286** [comment]
In my case I need to update more css for the buttons. Removing `box-shadow`. This is another css to be change for the button element.
`(ui.button(on_click=lambda: left_drawer.toggle(), icon='menu_open', color=None).tailwind.background_color('slate-200').text_color('slate-900').box_shadow('none'))`
The shadow is actualy set to `:before` prop. Tried setting `.tailwind('before:shadow-none')`, it didn't work.

![image](https://github.com/zauberzeug/nicegui/assets/13958935/636bc1ae-ddc1-4f35-8b6e-6f77771f9666)


The above fix worked for color (thanks @falkoschindler), but based on use case there are other classes need option to override undelaying css.
To avoid a long list of parameters, I think we add an option to disable default css for an ui element, then developer needs to provide full css as per requirements.
Alternatively, it could have option to set base theme(s), similar to MUI (react), where a developer can define and set to the ui object.

![image](https://github.com/zauberzeug/nicegui/assets/13958935/6da6b9e6-7e52-4247-a1a3-b3e1364a3ca2)

**Comment by falkoschindler** [comment]
@adityapant1286 Yes, styling the button is a bit tricky and I wish we would find a way to make it more intuitive. Suggestions are very welcome.
In this case, you can set `.props('unelevated')` to remove the shadow. I just found it in the documentation for [Quasar's button component](https://quasar.dev/vue-components/button).
