### ISSUE TITLE
Validation Element Error

### ISSUE THREAD

**Issue by GMezWheel** [zauberzeug/nicegui#3809]
### Description

Hi,
Sometimes I have this error :
```
File "/usr/local/lib/python3.10/dist-packages/nicegui/elements/mixins/validation_element.py", line 43, in error
    if self._error == error and self._props['error'] == new_error_prop:
KeyError: 'error'
```

Perhaps check that the key 'error' exists in the 'self._props' dictionary:
```py
if self._error == error and 'error' in self._props and self._props['error'] == new_error_prop:
```

**Comment by falkoschindler** [comment]
Hi @GMezWheel,

The "error" prop is set right in the initializer and never removed. So I don't immediately see a way this KeyError can occur.
Are you using the most recent version 2.2 of NiceGUI?
And can you, by any chance, provide a minimal reproducible example so we can investigate further? Thanks!

**Comment by GMezWheel** [comment]
No, I'm using the previous version of nicegui : 2.1.0.dev0

I'll upgrade to version 2.2 and let you know if the problem recurs.

Thanks for your quick help.

**Comment by kevinraymond** [comment]
I ran into this yesterday for the first time, on 2.2.0. Not sure what element OP is using, but mine is a select element. 

When it has `value=""` or `value=1`, for example, instead of `value=None` or a valid options label (e.g., 'Apple'), it's failing in the `ValidationElement.__init__` (probably in the super call to `ValueElement`. This causes the error prop to never be set.

Here's an example showing all three with a select element. I didn't try with any other input.

```
import traceback
from nicegui import ui

# fails
try:
    ui.select(
        label="Choose a fruit",
        options=["Apple", "Banana", "Cherry", "Date"],
        value=""
    )
except Exception as e:
    print("======================================")
    print("Empty string error:")
    traceback.print_exc()
    

# fails
try:
    ui.select(
        label="Choose a fruit",
        options=["Apple", "Banana", "Cherry", "Date"],
        value=1
    )
except Exception as e:
    print("======================================")
    print("Integer value error:")
    traceback.print_exc()

# works
ui.select(
    label="Choose a fruit",
    options=["Apple", "Banana", "Cherry", "Date"],
    value=None
)

ui.run()

# one potential option to fix is changing validation_element.py:
# if self._error == error and self._props['error'] == new_error_prop:
# to
# if self._error == error and self._props.get('error') == new_error_prop:
```

**Comment by arshad-muhammad** [comment]
@GMezWheel It looks like you're running into an issue because the code is trying to access the 'error' key in the self._props dictionary, but sometimes that key doesn’t exist, which throws a KeyError. To fix this, you can add a simple check to make sure the 'error' key is present before trying to use it.
Instead of just accessing self._props['error'] directly, you should first check if the key 'error' exists in the self._props dictionary.

**Comment by falkoschindler** [comment]
@arshad-muhammad He is referring to library code. If such a check is required, we'd need to fix it in the library code.

@GMezWheel Thanks for providing a reproduction! So it only seems to occur when initializing with an invalid value. I'll have a closer look into the traceback.

**Comment by falkoschindler** [comment]
I just created PR #3829 to address this issue. What do you think?

**Comment by kevinraymond** [comment]
That makes `None` an invalid value, so it should check for that explicitly.
