### ISSUE TITLE
Trello like drag and drop items between multiple cards.

### ISSUE THREAD

**Issue by kausar007** [zauberzeug/nicegui#397]
Is it possible to create a Trello like interface which uses drag and drop of items?
I can't seem to find anything. 

If not available then is it possible to add feature?

**Comment by rodja** [comment]
Thanks for reaching out. We would love to see build drag and drop support. Unfortunately Quasar decided to not include a build in solution (see https://github.com/quasarframework/quasar/issues/5890). Maybe you and/or others in this community can leverage one of the linked solutions and make it work....

**Comment by SebastienDorgan** [comment]
I think Quasar do not implement drag and drop because there is no real need for it. In HTML 5 everything is "draggable".
I have done a drag & drop datapipeline builder with NiceGUI:
![image](https://user-images.githubusercontent.com/12728415/219937010-96704158-f0b3-4842-a7a4-d8e6ff80a3a4.png)

What you have to do is to add the props "draggable" and bind the "dragend event" to the item you want to move around.
Hereunder, an extract from my code:

```python
def draggable_app_card(app: Application) -> int:
    with ui.card().tight().classes("rounded w-full px-2 py-1").props("draggable") as card:
        bind_drag_events_list(card, app)
        card_content(app)
        return card.id

def bind_drag_events_list(list_card: ui.card, app: Application):
    def on_list_card_drag_end(evt: Any):
        viewport_x = float(evt["args"]["pageX"])
        viewport_y = float(evt["args"]["pageY"])
        rec = state().drawing_area
        scene_x, scene_y = translate_to_card_center(viewport_x, viewport_y, rec)
        if rec is not None and inside(scene_x, scene_y, rec):
            m_id = str(uuid4())
            member = StreamMember(id=m_id, app_id=app.id, width=CARD_WIDTH, height=CARD_HEIGHT, x=scene_x, y=scene_y)
            model.add_stream_member(member)
            canvas_card = draw_canvas_card(app, scene_x, scene_y)
            state().set_member_card(member, canvas_card)
            bind_canvas_card_to_click(m_id, canvas_card)
            bind_drag_events_canvas(m_id, canvas_card)
            state().drop_area.update()

    list_card.on("dragend", on_list_card_drag_end, ["pageX", "pageY"])
```
Before somebody ask me :), I have also created a custom Scene2D NiceGUI component using Raphael.js to draw the arrows.
I do not share it yet because I think about replacing Raphael.js by konvajs, but if you are interested, let me know.

**Comment by falkoschindler** [comment]
Proof of concept for a Trello-like user interface:

```py
from __future__ import annotations
from nicegui import ui

class Column(ui.column):

    def __init__(self, name: str) -> None:
        super().__init__()
        with self.classes('bg-gray-200 p-4 rounded shadow'):
            ui.label(name).classes('text-bold')
        self.on('dragover.prevent', self.highlight)
        self.on('dragleave', self.unhighlight)
        self.on('drop', self.move_card)

    def highlight(self) -> None:
        self.classes(add='bg-gray-400')

    def unhighlight(self) -> None:
        self.classes(remove='bg-gray-400')

    def move_card(self) -> None:
        self.unhighlight()
        Card.dragged.parent_slot.parent.remove(Card.dragged)
        with self:
            Card(Card.dragged.text)

class Card(ui.card):
    dragged: Card | None = None

    def __init__(self, text: str) -> None:
        super().__init__()
        self.text = text
        with self.props('draggable').classes('w-40 cursor-pointer'):
            ui.label(self.text)
        self.on('dragstart', self.handle_dragstart)

    def handle_dragstart(self) -> None:
        Card.dragged = self

with ui.row():
    with Column('Next'):
        Card('Clean up the kitchen')
        Card('Do the laundry')
        Card('Go to the gym')
    with Column('Doing'):
        Card('Make dinner')
    with Column('Done'):
        Card('Buy groceries')

ui.run()
```

- As a possible drop target, the column handles the "dragover" and "dragleave" events to toggle background highlighting.
- In order to qualify as a drop target, the column calls `preventDefault()` via the Vue event modifier ".prevent".
- The card handles "dragstart" and stores the currently dragged card in a static field.
- The column handles "drop": It removes the dragged card from its current parent and adds a new card to itself. Note that we have to re-create the card UI because (currently) we can't move UI elements to a new parent in NiceGUI.

Of course the code leave much room for improvement. But it might be a starting point for re-implementing Trello. 😉

I'm not sure if we should add any of this to the NiceGUI implementation. Basic drag and drop is already possible, and everything else depends on the application.

**Comment by rodja** [comment]
> Proof of concept for a Trello-like user interface: ...

Wow, that is very impressive. We should put it into our list of examples!

**Comment by falkoschindler** [comment]
Ok, I added it to the examples: https://github.com/zauberzeug/nicegui/blob/main/examples/trello_cards/main.py

**Comment by kausar007** [comment]
> Proof of concept for a Trello-like user interface: ...

Oh wow. This is great. Thanks. I am not re-implementing Trello 😄. Creating a simple sorting app.

**Comment by infintropy** [comment]
> I think Quasar do not implement drag and drop because there is no real need for it. In HTML 5 everything is "draggable". I have done a drag & drop datapipeline builder with NiceGUI: ![image](https://user-images.githubusercontent.com/12728415/219937010-96704158-f0b3-4842-a7a4-d8e6ff80a3a4.png)
> 
> What you have to do is to add the props "draggable" and bind the "dragend event" to the item you want to move around. Hereunder, an extract from my code:
> 
> ```python
> def draggable_app_card(app: Application) -> int:
>     with ui.card().tight().classes("rounded w-full px-2 py-1").props("draggable") as card:
>         bind_drag_events_list(card, app)
>         card_content(app)
>         return card.id
> 
> def bind_drag_events_list(list_card: ui.card, app: Application):
>     def on_list_card_drag_end(evt: Any):
>         viewport_x = float(evt["args"]["pageX"])
>         viewport_y = float(evt["args"]["pageY"])
>         rec = state().drawing_area
>         scene_x, scene_y = translate_to_card_center(viewport_x, viewport_y, rec)
>         if rec is not None and inside(scene_x, scene_y, rec):
>             m_id = str(uuid4())
>             member = StreamMember(id=m_id, app_id=app.id, width=CARD_WIDTH, height=CARD_HEIGHT, x=scene_x, y=scene_y)
>             model.add_stream_member(member)
>             canvas_card = draw_canvas_card(app, scene_x, scene_y)
>             state().set_member_card(member, canvas_card)
>             bind_canvas_card_to_click(m_id, canvas_card)
>             bind_drag_events_canvas(m_id, canvas_card)
>             state().drop_area.update()
> 
>     list_card.on("dragend", on_list_card_drag_end, ["pageX", "pageY"])
> ```
> 
> Before somebody ask me :), I have also created a custom Scene2D NiceGUI component using Raphael.js to draw the arrows. I do not share it yet because I think about replacing Raphael.js by konvajs, but if you are interested, let me know.

@SebastienDorgan very interested!

**Comment by brianlah87** [comment]
Do we currently have access to dataTransfer in the dragstart and drop event?

**Comment by falkoschindler** [comment]
@brianlah87 As far as I know there's currently no way to use `dataTransfer` because the JavaScript event is long gone when we consume a drag event on the server.
Maybe we could implement a way to run arbitrary JavaScript code when an event happens, e.g. by passing a string to an event handler... 🤔

**Comment by brianlah87** [comment]
Ah, I see.

In the example above, the dragged card is stored as a class variable which would be shared between all connected clients so drag events coming from different clients would interfere with one another.

What is the intended way to do drag and drop that works with multiple clients?

**Comment by brianlah87** [comment]
In that example, the instance of the manager class holding `dragged` would then need be within to the generator function decorated with `@ui.page` in order the clients to not share that state, right?

I think that's where I'm having the issue - because the objects I'm implementing drag and drop are in a globally scoped `@ui.refreshable` function, to allow `refresh()` to update the views on different clients whenever the data changes (which saves a ton of code)

I was thinking to track everyone is dragging in some globally accessible dict, but that doesn't seem very elegant so I'm not wondering if I'm going about it all the wrong way.

**Comment by brianlah87** [comment]
I notice in the Trello cards sample code, @falkoschindler does not use the `dragend` event, but @SebastienDorgan uses it in his example.

Strangely, `dragend` on the item being dragged never seems to fire in my own testing, but having the drag target implement `drop` works just fine.

Am I missing something here?

**Comment by falkoschindler** [comment]
Hard to tell why dragend isn't fired. Usually both events work as expected:
```py
with ui.card().props('draggable') \
        .on('dragstart', lambda: ui.notify('start')) \
        .on('dragend', lambda: ui.notify('end')):
    ui.label('Drag me!')
```

If it keeps bugging you, I suggest to open a new discussion with an [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) so we can play around with the issue more easily. 🙂

**Comment by brianlah87** [comment]
Thanks for the hint! I figured it out, my bad.

The dragged element was part of a shared `ui.refreshable`, and I was refreshing it in the `dragstart` event to propagate style changes to other clients as well as remove the `draggable` prop when the element is picked up.

Since everything gets torn down and rebuild whenever `refresh()` is called, that's probably why the `dragend` event never fired.

I'll try to find another way to update other clients on drag state. I don't suppose there's any point opening a new thread with an MRE now, since its obviously a problem with my app model.
