### ISSUE TITLE
Ability to set custom text on the button of Upload component

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#40]
I'd like to have custom text on the button of Upload component. Currently it is hardcoded as "Upload".

As far as I understand, I can manually recreate the component by copying and changing its source code, but still, some customizations readily available ("Upload" button appearance too? or even custom Form component?) would be nice.

Also it would probably be useful to clear the Input component of the upload form after the upload button is clicked.

**Comment by falkoschindler** [comment]
I finally added an argument `upload_button_text` for the upload element: https://github.com/zauberzeug/nicegui/commit/0880ca03a3f05b9287f4de33825d901d5f6d68b6

Right now, I can't find a way to reset the file input. Maybe you have an implementation? Otherwise, I'd leave it as is. The upload element is certainly an example for a piece of UI that could be styled and customized in so many ways that it might be easier to copy and modify its source code rather than providing all options in the library. On the other hand, for a quick file upload it's good enough.

**Comment by falkoschindler** [comment]
I finally found a solution for clearing `ui.upload`: https://github.com/zauberzeug/nicegui/discussions/185#discussioncomment-4260496
