### ISSUE TITLE
ui.html embed tag seem to ignore width and height percentage but renders correctly with pixels

### ISSUE THREAD

**Issue by vmlstandard** [zauberzeug/nicegui#4097]
Based on this:
```py
path = app.add_static_file(local_file='/Users/falko/some.pdf')
ui.html(f'<embed src="{path}" type="application/pdf" width="100%" height="100%">')
```

_Originally posted by @falkoschindler in https://github.com/zauberzeug/nicegui/discussions/1132#discussioncomment-6371522_

This doesn't resize correctly in the browser:

```py
from nicegui import app, ui

path = app.add_static_file(local_file='<some_pdf.pdf>')
ui.html(f'<embed src="{path}" type="application/pdf" width="100%" height="100%">')
ui.run()
```

But this one does:

```py
from nicegui import ui

path = app.add_static_file(local_file='<some_pdf.pdf>')
ui.html(f'<embed src="{path}" type="application/pdf" width="1000" height="700">')
ui.run()
```

Am I missing something? I probably am. Please let me know. Thank you.

**Comment by falkoschindler** [comment]
Hi @vmlstandard,

HTML doesn't support width and height attributes with units, which is why this is invalid:
```html
<embed src="{path}" type="application/pdf" width="100%" height="100%">
```

Using unit-less dimensions works, but doesn't scale with the page size:
```html
<embed src="{path}" type="application/pdf" width="1000" height="700">
```

To automatically scale the embedded object to the full size of the view port, you can use CSS with units "vw" (view width) and "vh" (view height). To compensate for 1rem padding on each side, you can use the `calc()` function:
```html
<embed src="{path}" type="application/pdf" style="width: calc(100vw - 2rem); height: calc(100vh - 2rem);">
```
