### ISSUE TITLE
ui.table does not have the same theme as the ui.run

### ISSUE THREAD

**Issue by johancj** [zauberzeug/nicegui#413]
Hi,

When using ui.run in dark mode, the ui.table does not automatically change to the same theme. 

- Is there a way to sync the theme in ui.table to ui.run?

Example code:
```py
from nicegui import ui

table = ui.table({
    'columnDefs': [
        {'headerName': 'Name', 'field': 'name'},
        {'headerName': 'Age', 'field': 'age'},
    ],
    'rowData': [
        {'name': 'Alice', 'age': 18},
        {'name': 'Bob', 'age': 21},
        {'name': 'Carol', 'age': 42},
    ],
    'rowSelection': 'multiple',
}).classes('max-h-40')


ui.run(dark=True)
```

Best regards,
Johan Christian Jenssen

**Comment by Allen-Taylor** [comment]
You can add a theme when you create the table. 

```
table = ui.table({
    'columnDefs': [
        {'headerName': 'Name', 'field': 'name'},
        {'headerName': 'Age', 'field': 'age'},
    ],
    'rowData': [
        {'name': 'Alice', 'age': 18},
        {'name': 'Bob', 'age': 21},
        {'name': 'Carol', 'age': 42},
    ],
    'rowSelection': 'multiple',
}, theme="balham-dark").classes('max-h-40')

```

**Comment by johancj** [comment]
Yes, but I would prefer to do this dynamically. For example if ui.run(dark=None).

**Comment by Allen-Taylor** [comment]
> I would prefer to do this dynamically. For example if ui.run(dark=None).

Pretty sure this is because NiceGUI uses AG-GRID instead of Quasar Tables.

**Comment by falkoschindler** [comment]
Thanks for pointing this out, @johancj. Currently, we use Quasar for switching between light and dark mode. But since `ui.table` is no Quasar element ([yet](https://github.com/zauberzeug/nicegui/issues/370)), it is not affected.

This issue relates to https://github.com/zauberzeug/nicegui/discussions/342 where we think about a better dark mode integration, e.g. allowing the user to switch the mode manually.

**Comment by falkoschindler** [comment]
I'll close this issue, since we can't really do anything about it apart from the steps we already identified:

- #342 for better dark mode integration (then you could subscribe to some change event and update the grid accordingly)
- #370 for using QTable instead of AG Grid for `ui.table` (then the theme should switch automatically)
