### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by Quadrum1** [zauberzeug/nicegui#439]
First off, thanks a ton for this GUI tool! 
It allows for some great looking applications while still being easy to develop and add to existing code.

Now to my issue: Advanced use-cases are not covered by the reference!
I don't know how wide-spread this issue really is, but I have started to notice it while working on tables.
The reference, as well as the comments in code, show nothing about two of three arguments.

I found that pretty sketchy, so I took a deeper look at the methods the ui.table class offers. Turns out quite a lot.
Problem is, I find no reference for a majority of those methods.
I know that table inherits from a parent class, but that parent (Element) is not listed at all in the docs.

Now this might be unique for tables (maybe you don't like them, I don't judge), but I think this might apply to more than just tables.
So now to my general suggestion:

It would really help for developing with NiceGUI if all methods are listed _and_ explained. 
This does not even require any example code. I believe the basic examples in reference are already great and sufficient for starting.
Would make it much quicker to figure out what each Element is truly capable off, instead of digging trough source code while trying to figure it out. Good documentation practice can vastly improve dev-experience, and might even help NiceGUI development if you want to look something up instead of searching in the code :)

Cheers.
[Example Documentation](https://docs.python.org/3/library/time.html)

---

Task list:

- [x] add links to subpages with more examples
- [x] allow adding multiple examples per element
- [x] rename "reference" to "documentation" (forward old endpoint)
- [x] use consistent terms for "examples" (example folder on GitHub) and "demos" (online snippets on website)
- [x] automatically generate documentation for each element
- [x] add `ui.element` to the API reference

**Comment by falkoschindler** [comment]
Thanks, @Quadrum1, for bringing up this issue. We totally agree with your observation: The documentation is sketchy. In other words, it needs to catch up with the quickly growing library.

Originally, we focussed on showing the class docstring and demonstrating the most basic use case for each element. And most elements and their APIs are intentionally kept simple. Many methods of the `Element` base class, for example, are for internal use only and thus undocumented. But it turned out that many users of NiceGUI have very specific applications in mind and push the limit of what is officially or unofficially possible with NiceGUI. And, of course, we try to make things possible if they are in line with NiceGUIs overall philosophy. Now elements like `ui.table` have a bit more to offer than what is shown on [nicegui.io](https://nicegui.io/). Somehow we used to think it is enough (for a start) to add documentation in form of docstrings, but people expect an exhaustive online documentation from a serious, grown-up Python library, especially if there is a page called "API _reference_".

So we came up with the following plan to tackle this issue:

1. Add an example for `ui.element` to the API reference. This is the only missing UI element I'm aware of.
2. Add links to separate pages /reference/[element] for each UI element. This keeps the reference page from growing even more while giving each element more room for a detailed explanation.
3. Automatically generate a documentation for each element, its properties, and methods from docstrings.
4. Allow adding multiple examples per element. The reference page could auto-detect [element].example.py files and show them on the element's detal page. Existing examples from reference.py can move into these separate files. This not only cleans up the lengthy reference.py, but also encurages adding more and more examples, which will nicely complement the documentation.

Maybe on follow-up issues:

5. Implement a global search function to search across all documentation pages.
6. Present demos from the example folder more prominently, e.g. with a screenshot. They contain advanced use cases that are not easily shown in a live demo, but can be valuable for the community and sometimes might be overlooked.

**Comment by alikalik9** [comment]
I agree, I really like NiceGUI, but as someone with Intermediate Python knowledge and no Quasar/tailwind experience, a complete documentation would be really apreciated.

**Comment by rodja** [comment]
Looks really good. I think you can merge anytime. Just a few things we might consider:

- hiding the "Methods" subsection if an element has not methods
- the arrow-link-indicator-icon is missing behind more...
- we may want to put the parameter list on the individual subpages to reduce clutter:

<img width="1073" alt="Screen Shot 2023-03-24 at 10 05 32" src="https://user-images.githubusercontent.com/131391/227475588-7c6184e5-ce20-4c39-a5cd-c7de0fd4c1b2.png">

**Comment by falkoschindler** [comment]
I'll close this issue as completed. Of course we can (and should) continuously improve the documentation when adding new features or posting new code examples in GitHub discussions.

**Comment by rodja** [comment]
We just deployed the new documentation to https://nicegui.io. By introducing the ability to present subpages for individual elements we now have the infrastructure to use multiple, more complex demos in the documentation. We are eager to see pull-requests from the community for adding this kind of content.
