### ISSUE TITLE
return values from ui.run_javascript

### ISSUE THREAD

**Issue by hub-il** [zauberzeug/nicegui#440]
I am trying to get the file paths returned from window.showOpenFilePicker() but it returns an empty dictionary `[{}]`.  I'm not sure if this is a bug or I am implementing it wrong.

~~~~py
from nicegui import ui

async def file_picker():
    file_list = await ui.run_javascript(f'window.showOpenFilePicker()', respond=True, timeout=500)
    print(file_list)

ui.button('Choose file', on_click=file_picker)
ui.run()
~~~~

**Comment by Diegiwg** [comment]
I tried here, and I couldn't get 'the path'.

From what I understand of the `showOpenFilePicker` API, it returns a `FileSystemFileHandle`, which has the `getFile` method, which returns a `File`.

The file, in turn, has the information:

- lastModified
- name
- webkitRelativePath
- size
- type
- and has the `text` method, which returns the contents of the file.

Therefore, I believe that you cannot get the file path with this API.

**Comment by falkoschindler** [comment]
To get the result from `showOpenFilePicker`, we need to consider a few things:

- `showOpenFilePicker` is an async function, so we need to `await` it on the client side.
- For async JavaScript functions we need to add a `return` statement. (We should probably improve the documentation for async JavaScript...)
- As @Diegiwg mentioned, the result is an array of `FileSystemFileHandle`, which doesn't seem to be JSON-serializable. Therefore I would map it to a plain JavaScript object or - like in the example below - pick the information your need, e.g. the file name.
- Because the user has to interact before the function can return, the timeout needs to be long enough. But you chose 500 seconds, which is plenty. (NiceGUI uses the standard SI unit "seconds" instead of "milliseconds".)

```py
async def file_picker():
    file_list = await ui.run_javascript('return (await window.showOpenFilePicker()).map(f => f.name)', respond=True, timeout=5000)
    print(file_list, flush=True)

ui.button('Choose file', on_click=file_picker)
```

**But** this does not give you the file _paths_ for the reasons discussed in #283. Maybe the [local file picker](https://github.com/zauberzeug/nicegui/tree/main/examples/local_file_picker) is what you're looking for? It didn't make it into the public API yet, but exists as a proof of concept in our examples collection.

**Comment by falkoschindler** [comment]
@hub-il Could you solve the problem with getting a response from `showOpenFilePicker`? And have you looked into https://github.com/zauberzeug/nicegui/discussions/283 and the [local file picker](https://github.com/zauberzeug/nicegui/tree/main/examples/local_file_picker)?

**Comment by falkoschindler** [comment]
@hub-il I'll close this issue as completed. Feel free to reopen it if the problem persists.
