### ISSUE TITLE
Radio on_change handler does not allow async handler

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#48]
```python3
async def on_analogue_input_change(cls):
    pass

# later...
ui.radio({1: ''}, on_change=on_analogue_input_change).bind_value(model, 'radio_value')
```

I get when running the app:
```
Traceback (most recent call last):
  File "/home/debian/venv/lib/python3.7/site-packages/nicegui/events.py", line 234, in handle_event
    create_task(result, name=str(handler))
  File "/home/debian/venv/lib/python3.7/site-packages/nicegui/task_logger.py", line 29, in create_task
    loop = asyncio.get_running_loop()
RuntimeError: no running event loop
/home/debian/venv/lib/python3.7/site-packages/nicegui/elements/value_element.py:12: RuntimeWarning: coroutine 'on_analogue_input_change' was never awaited
  sender.change_handler, ValueChangeEventArguments(sender=sender, socket=None, value=value)))
```

There is no such error if `on_change` is a sync function.

**Comment by falkoschindler** [comment]
Thanks for reporting this issue!

This is not only the case for radios, but all value elements. The binding expression causes the value to change. But since NiceGUI is not running yet, there is no event loop to handle the async callback. Here is a minimum reproduction:

```
from nicegui import ui

async def handle():
    pass

model = type('', (), {'x': True})
ui.switch(on_change=handle).bind_value(model, 'x')

ui.run()
```

We'll have to think about a solution.

Meanwhile, a workaround is to set the initial UI value to the model value:

```
ui.switch(value=model.x, on_change=handle).bind_value(model, 'x')
```

**Comment by falkoschindler** [comment]
Ok, we found a solution: If there is no running event loop, we simply schedule async event handlers to be executed on startup: https://github.com/zauberzeug/nicegui/commit/52863b554b99f33f0285106f0a77379d51365278
