### ISSUE TITLE
A question about component update moment in the page lifecycle

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#50]
I have a page with `on_connect` handler. In this handler, I start some tasks with `asyncio.create_task`:
```python
cls.messages_tasks = [
    asyncio.create_task(cls.handle_di_messages(cls.mqtt_client)),
    asyncio.create_task(cls.handle_ai_messages(cls.mqtt_client)),
    asyncio.create_task(cls.handle_tc_messages(cls.mqtt_client)),
    asyncio.create_task(cls.refresh_aout_values(cls.mqtt_client)),
]
```
Several tasks are ongoing and the last of them is single-shot. They all are async as they request and receive values from MQTT broker.
What I experience is that I receive the message from MQTT broker in the last task, but the corresponding UI elements are sometimes not updated.

I suspect this is due to the asynchronous nature of the task:
- if the response comes quicker than the page is rendered, it's ok
- if the response comes after the websocket connection is established, it's ok
- but if the response comes between the page has been loaded, but before the websocket connection is up, then the component update is lost.

Please share your thoughts on the matter - am I right? Is it possible to check it somehow?

I currently fixed it by `await`ing the single-shot task instead of putting it to the common list of running tasks.
Is this fix good or it's a hackish way to work around the problem?

**Comment by falkoschindler** [comment]
Your question *might* be related to the breaking change in version 0.8. Before, we made use of the underlying JustPy framework to automatically update the UI after event handlers (if not actively prevented with a `return False` at the end). Now NiceGUI still updates most elements automatically (e.g. a label is updated after setting its text property), but some updates you might have to trigger explicitly yourself. Can you give more details about what should happen in the UI? Or maybe you can boil it down to a minimum example code?

The following example shows the current date and time after a new client has connected. Although there's a delay of 1 second (and the page is updated and rendered), setting `label.text` triggers an update for this UI element. Its state is sent to the client which updates the UI in the browser.

```python3
import asyncio
from datetime import datetime

from nicegui import ui

async def connect():
    await asyncio.sleep(1.0)
    label.text = datetime.now().isoformat()

with ui.page('/page', on_connect=connect):
    label = ui.label()

ui.run()
```

---

But probably you're aware of all that and the question is deeper: Is it possible that an update does not reach the client because the connection is not yet established? As far as I understand, the complete state of a page is held on the server (in Python world) for new clients. When they connect, they get the complete state of that page. I don't see how they could miss an update.

In your example the tasks are even only started after a new connection is created. So how should this connection not be ready when the MTTQ response updates the UI?

You write "but if the response comes between the page has been loaded, but before the websocket connection is up, then the component update is lost." - What do you mean with "loaded"? Doesn't the client "load" the page after establishing a websocket connection?

**Comment by me21** [comment]
> In your example the tasks are even only started after a new connection is created. So how should this connection not be ready when the MTTQ response updates the UI?

There are actually two connections: HTML connection and websocket connection. The `on_connect` handler is fired when the HTML connection is established, but obviously before the websocket connection, because the websocket is created by the page's javascript.

> You write "but if the response comes between the page has been loaded, but before the websocket connection is up, then the component update is lost." - What do you mean with "loaded"? Doesn't the client "load" the page after establishing a websocket connection?

In my understanding, `on_connect` handler is called when the browser requests the page. This means that the websocket connection is not yet established, because it needs the page to be fully loaded in the browser, including javascript, because websocket connection is started by javascript.

So, as I see it, the process is as follows:
1. We open new tab in the browser and open the NiceGUI webpage in it.
2. The browser requests the page from NiceGUI server.
3. `on_connect` is fired.
4. In my example, async tasks are started.
5. NiceGUI prepares HTML file with the initial components state and sends it to the browser.
6. Browser starts executing the javascript on the webpage and starts websocket connection.

What would happen if the MQTT response that updates the UI arrives after 4., but before 6. is completed?

**Comment by falkoschindler** [comment]
Oh, I see! `on_connect` is called as part of the routing generating the HTML page, "way" before the socket connection is created. You're absolutely right: Changes to the UI that happen after `on_connect` returns and before the socket is connected do not reach the client.

Here is a reproduction:

```python
import asyncio
from nicegui import ui

async def on_connect():
    label.text = 'loading...'
    asyncio.create_task(takes_a_while())

async def takes_a_while():
    await asyncio.sleep(0.1)
    label.text = 'done'

with ui.page('/page', on_connect=on_connect):
    label = ui.label()

ui.run()
```

With a delay of 0.1s the text "done" never appears. It's the same when removing the delay completely. But a delay of 1.0s works on my machine.

I have to think about if and how we could fix this problem. Maybe we can somehow keep track of UI updates on pages that are still connecting. These updates should be delivered once the socket is open.

As a workaround I would add a delayed UI update to make sure there is an update after the socket connected. This might be a component update (e.g. `label.update()`) or even a whole page update (`await label.page.update()`).

```python
async def takes_a_while():
    await asyncio.sleep(0.1)
    label.text = 'done'
    await asyncio.sleep(1.0)
    label.update()
```

**Comment by me21** [comment]
Or maybe just call `on_connect` only after the websocket is connected and thus the page is fully functional.

**Comment by falkoschindler** [comment]
@hroemer

**Maybe you could point to some documentation of how things work out here?**

You've probably seen [nicegui.io](https://nicegui.io/). That's the only documentation at the moment. More detailed explanations can be found in GitHub issues and discussions. I probably should add some links in a Q&A section.

**How are you supposed to change state of a component such as the label in your example above for any given larger UI?**

A function like `ui.label()` is actually a constructor of a NiceGUI element, which registers itself with the UI. You can store the resulting object wherever you want for later reference. Here is, for example, a "WifiButton" from the library *RoSys*: https://github.com/zauberzeug/rosys/blob/79c2c1dd8fabd0086fa4d4231f5bd6127291006a/rosys/system/wifi_button_.py#L38. It derives from `ui.button`, sets the `on_click` event handler and some `props`, defines a `ui.dialog` and creates a `ui.timer` to regularly update itself and its child elements. An explicit UI update is usually not needed. This way you can encapsulate groups of UI elements into classes and use them in higher-level code.

**Where are the references/names actually "stored"?**

NiceGUI itself doesn't explicitly store UI elements, but only creates JustPy views. If you need the elements, you should hold them yourself as mentioned above. Usually you shouldn't need to tap into nicegui.globals like `page_stack`. These are primarily for internal use.

**Comment by falkoschindler** [comment]
@hroemer Let me see...

- The issue with setting `reload` to `True` or `False` is because your `ui` is a `Page` object, not a `Ui`. Your main.py should look more like this:

  ```python
  from nicegui import ui
  from sample_page import SamplePage

  SamplePage()

  ui.run(reload=True, host='127.0.0.1', port=8000, dark=True)
  ```

  In the original code NiceGUI's pre-evaluation of `ui.run` (in order to know how to start the uvicorn server while importing `ui`) is working, although actually *calling* `ui.run` does not work. Long story short: `ui` should be the `Ui` object imported from `nicegui`.

  The instantiated object of type `SamplePage` isn't needed anymore, since it already registered itself with the UI as a side-effect. You can follow the style of NiceGUI and write it like a function and like the other UI elements:

  ```python
  ...
  from sample_page import SamplePage as sample_page

  sample_page()
  ...
  ```

- The initializer of `SamplePage` also needs some corrections:

  ```python
      def __init__(self) -> None:
          # call base initializer first:
          super().__init__(route='/page', title='repr page', on_page_ready=self.on_page_ready)
          # now work within the `self` context:
          with self:
              self.label = ui.label('Any label')
              # calling `update()` is not necessary
              row = ui.row()
              ui.button('+', on_click=lambda: self.add_elements(row))
              with ui.card():
                  with ui.row():
                      ui.label('Hello world!')
  ```

  The rest should be working as expected.

Well well, NiceGUI definitely needs more documentation about building such custom elements or pages...

**Comment by falkoschindler** [comment]
**`page_stack` and `view_stack`**

They are used internally to keep track of which context is currently open and, thus, where to add an element. If you write

```python
with ui.card():
    ui.label('A')
    with ui.row():
        ui.label('B')
        ui.label('C')
    ui.label('D')
```

first a `ui.card` is added to the `view_stack`. Therefore, the label "A" is added to this card. After entering `ui.row`, the next two labels are added to the new top element, i.e. the row. After leaving and popping the row again, label "D" is added to the card.
The `page_stack` behaves similarly.

**Changing the main page**

NiceGUI is intended to be easy to start with. So a three line hello world

```python3
from nicegui import ui
ui.label('Hello world!')
ui.run()
```

should simply work. This implies quite a lot (yes, we know, explicit is better than implicit...), e.g. how the server is started and that there is a main page at route "/". This page is automatically pushed to the `page_stack` and remains there. If an element is not explicitly added to a different page, it is added to "/".

Changing the main page is currently a bit tricky. You can get a reference from the first item on the `page_stack`:

```python3
from nicegui.globals import page_stack

main_page = page_stack[0]
main_page.dark = True
with main_page:
    ui.label('Hi!')
```

On the other hand it should also be ok to create a new page with route "/". Yes, then there are two routes with path "/", but since new pages insert their routes before others, it should work.

```python3
with ui.page('/', dark=True):
    ui.label('Hi!')
```

It also might be useful to define a `MainPage` class:

```python3
class MainPage(ui.page):
    def __init__(self):
        super().__init__('/', dark=True)
        with self:
            ui.label('Hi!')

MainPage()
```

I'll think about whether NiceGUI should automatically remove routes that are overwritten by new pages. The implementation, however, could be challenging, since we would also need to replace the page in the `page_stack`...
