### ISSUE TITLE
wrongly thinks I am running interactive

### ISSUE THREAD

**Issue by dentad** [zauberzeug/nicegui#56]
I am using click to write a cli tool, that has an option of showing some web interactive things.

Nicegui is wrongly assuming that I am running interactively, and .run() will not work.

I note that I do not have a main.py and no file has the usual
```python
if __name__ == '__main__':
    main()
```
boilerplate - in fact I dont even know if this is important to nicegui.

**Comment by falkoschindler** [comment]
Are you looking for something like this?

```python3
#!/usr/bin/env python3
import webbrowser
import click
from nicegui import ui

@click.command()
@click.option('--name', prompt='Your name', help='The person to greet.')
def hello(name):
    click.echo(f'Hello {name}!')
    ui.label(f'Hello {name}!')
    webbrowser.open('http://0.0.0.0:8080/')

ui.on_startup(lambda: hello(standalone_mode=False))

ui.run(reload=False, show=False)
```

NiceGUI needs to start its server via `ui.run`, which blocks throughout the whole lifetime of the application. But `on_startup` you can start a click command with `standalone_mode=False`. In order to hide the website until the name is entered, I'd start NiceGUI with `show=False` and open the browser with `webbrowser.open` explicitly.

(The current implementation of NiceGUI's "interactive mode" is a bit confusing and - I think - broken. So you basically always need a `ui.run`.)

**Comment by dentad** [comment]
This is my current code
```python
@click.command()
def window():
    """Window to the Kube"""

    ui.checkbox("Hello, world!")

    ui.run(host="127.0.0.1", port=8079, title="Kora")  #, exclude="customexample,highcharts,interactiveimage,keyboard,matplotlib,nipple,three")
```
which gives me this output with nicegui 0.8.7
```sh
❯ mytool window
Could not find and pre-evaluate ui.run(). Starting interactive mode without auto-reload.
Error: Unexpected ui.run() in interactive mode.
```

**Comment by falkoschindler** [comment]
`ui.run()` needs to move out of `hello()`. That means the uvicorn-Server starts at the end of the main script, not as part of the click command.
