### ISSUE TITLE
File upload stops at 99.99%

### ISSUE THREAD

**Issue by 2000Nic** [zauberzeug/nicegui#585]
When using ui.upload in the latest version of Chrome it stops when it reaches 99.99%.
`ui.upload(auto_upload=True)`

**Comment by 2000Nic** [comment]
I just realized that we don't know how to use the file after uploaded... Do you turn it into a variable like below?
`image = ui.upload()`
The documentation around the upload element seems overly simplified

**Comment by falkoschindler** [comment]
I'll close this issue due to inactivity. But feel free to re-open it once you have new information for us, @2000Nic!

**Comment by AlexYRM** [comment]
I know the issue is closed, but I have a similar problem and I would really use some help. I would like to send the uploaded file (in my case a PDF) through requests to FastAPI. 
I have tried your code and get this error: "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 10: invalid continuation byte"
As @2000Nic said I do not know how to handle the uploaded file. 
Thank you!

**Comment by 2000Nic** [comment]
I ended up fixing my problem with the code:

```
from nicegui import events, ui
from PIL import Image

def handle_upload(event: events.UploadEventArguments):
    with event.content as f:
        uploaded_file = Image.open(f)
        uploaded_file.save("moin.jpg")

ui.upload(on_upload=handle_upload)

ui.run()
```

As I was trying to use an image with cv2. After this cv2.imread("moin.jpg" worked for the rest.

In your case with .pdf files I'd guess the following would work.

```
from nicegui import events, ui

def handle_upload(event: events.UploadEventArguments):
    with event.content as f:
        file = open('somefile.pdf', 'wb')
        for line in f.readlines():
            file.write(line)
        file.close()
ui.upload(on_upload=handle_upload)

ui.run()
```

After this you can do whatever you need to with the newly stored somefile.pdf
