### ISSUE TITLE
client.content.classes(remove='q-pa-md') no longer removes padding

### ISSUE THREAD

**Issue by chook100** [zauberzeug/nicegui#596]
Hello. After updating to NiceGUI 1.2.0, I have noticed that `client.content.classes(remove='q-pa-md')` no longer removes the padding on the site. It does not error out or anything, it just does not remove the padding.

**Comment by falkoschindler** [comment]
Sorry, this is a breaking change that originates from the Tailwind update we did in 1.2.0. Because Tailwind changed the way they handle conflicting classes, it got more difficult to overwrite, e.g., a default row gap of "gap-4" with something like "gap-0". Therefore we replace default classes with default CSS. This solves the problem with Tailwind's new behavior, but changes the layout in cases where you rely on certain classes to be assigned to an element.

To be more specific, the `content` does not have a class `q-pa-md` anymore. To remove the padding, simply add a Tailwind class 'p-0' or a style definition `padding: 0`.
