### ISSUE TITLE
Typo in page_ready_handler

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#60]
https://github.com/zauberzeug/nicegui/blob/d4bea2fcea2b90b5780cb3eefc7eb4c8cd1b3ca3/nicegui/elements/page.py#L82

I believe `msg.socket` should read `msg.websocket` instead based on inspecting `msg` variable. Otherwise, the argument passed to page ready handler is empty string.

Also is it possible to provide session_id argument in page ready handler in addition to websocket instance? Although it's not high priority, as it's possible to get it as `websocket.cookies['jp_token']`.

**Comment by falkoschindler** [comment]
Oh, thanks for pointing out this typo! It's fixed in https://github.com/zauberzeug/nicegui/commit/67c41c1904f0b8c9807b92ccf58951b44f62092d.

I'm not sure about adding another argument. If you can live with `websocket.cookies['jp_token']`, I'd leave it as it is for now. To make additional information more accessible, I'll have to think about replacing the socket with an event argument object like the others defined in https://github.com/zauberzeug/nicegui/blob/main/nicegui/events.py. That's probably the way to go anyway.
