### ISSUE TITLE
Custom elements like ui.interactive_image are not properly replaced due to Vue's "in-place" patching

### ISSUE THREAD

**Issue by DavidLeBonk** [zauberzeug/nicegui#600]
Basically I am working on learning some pagination, when the item is updated via ui.update() the text updates fine but the images only update after I switch into another ui.tab and return

https://i.imgur.com/zSNFzDi.gif

---

Task list:

- [x] write pytest to check all custom components for this bug
- [x] PR #616
- [x] PR #624
- [x] add unique key props as workaround
- [ ] fix `ui.aggrid`
- [ ] fix `ui.chart`
- [ ] fix `ui.colors`
- [ ] fix `ui.log`
- [ ] fix `ui.scene`

**Comment by rodja** [comment]
This sounds like a caching issue. Please have a look at #588.

**Comment by DavidLeBonk** [comment]
https://i.imgur.com/RkWAu1Q.png Added this, same issue. Using Chrome

**Comment by DavidLeBonk** [comment]
UPDATE: I have managed to make it work using set source, when redefining the entire element it doesnt work but when referncing the element and running .set_source( it updates)

**Comment by falkoschindler** [comment]
If the problem persists even when appending a unique ID, it doesn't seem to be a caching problem.

@DavidLeBonk Can you, please, provide source code of a [minimum reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) demonstrating the problem?

**Comment by DavidLeBonk** [comment]
I will attempt to do so tomorrow 👍

**Comment by DavidLeBonk** [comment]
Here is a small piece of code that allowed me to re-create the bug, I am trying my hand at writing something akin to a rewrite of VRCX, a popular open source API utility.

`import uuid
from nicegui import ui

def reload():
    rowItem.clear()
    with rowItem:
        ui.button("Clicked", on_click=reload).style("height: 100%; width: 100%;")
        ui.label(f"Updated text").style("height: 100%; width: 100%; font-size: 2em; text-align: center;")
        ui.interactive_image(f"https://api.vrchat.cloud/api/1/file/file_67892034-a3dd-472b-a74a-46f372940e3c/1/file?dummy={uuid.uuid4()}").style("width: 22em;")
    ui.update(rowItem)

rowItem = ui.row()
with rowItem:
    ui.button("Test", on_click=reload).style("height: 100%; width: 100%;")
    ui.label(f"Text").style("height: 100%; width: 100%; font-size: 2em; text-align: center;")
    ui.interactive_image(f"https://api.vrchat.cloud/api/1/file/file_35ef449a-33fd-49b1-a2d9-111ba4156408/2/file?dummy={uuid.uuid4()}").style("width: 22em;")
ui.run(dark=True)`

**Comment by rodja** [comment]
Wow, thats really serious and has nothing to do with caching, I guess. While experimenting with the behaviour I further boiled it down to this example:

```py
async def reload():
    content.clear()
    # await asyncio.sleep(0.01)
    with content:
        ui.interactive_image('https://picsum.photos/id/377/640/360')
        ui.label('should show new image, but doesnt').classes('w-full text-center')


with ui.row().classes('w-64') as content:
    ui.interactive_image('https://picsum.photos/id/29/640/360')
    ui.button("Test", on_click=reload).classes('w-full')
```

The `src` of the image is not updated correctly:

![src-not-updated](https://user-images.githubusercontent.com/131391/227103891-d2b31f76-23d7-41a6-b253-a68675a6b762.gif)

If I uncomment the async delay everything works as expected.

**Comment by DavidLeBonk** [comment]
Happy to help👍

**Comment by rodja** [comment]
Wow. @falkoschindler and me investigated the error a bit and -- without any expectations asked ChatGPT:

<img width="743" alt="Screen Shot 2023-03-23 at 13 37 39" src="https://user-images.githubusercontent.com/131391/227206057-6b542b7a-ca96-4b9d-a393-e641a406a214.png">

**Comment by falkoschindler** [comment]
Interestingly, the SVG content of an interactive image _is_ updated. Only the source remains unchanged.

By the way, the problem also occurs with `ui.scene`, but not with `ui.markdown`.

**Comment by dclause** [comment]
I have taken a look at it but @rodja and chatGPT actually answered it first :p 
The reason behind is indeed the DOM reusage. Vue is smart enough to detect that the dom won't change, hence won't replace it.

From Vue point of view, it is manipulating the template within the `template` key of interactive_image.js. The rest is done in vanilla JS outside the view of Vue. It can know what you are doing with it, hence, can't optimize / update / work properly.

Two solutions: 
- introduce something that makes the DOM differ (for instance a randomly generated key)  => that would be an easy workaround with not much rework.
- rewrite the JS into a proper "vue only" way to write it. => this is tricky because we have to bind dynamically defined events from the props to dynamically created methods. I don't think this kind of trick is documented.

I just created a PR #616 to demonstrate solution 2, up to you to decide your favourite way.

**Comment by falkoschindler** [comment]
@dclause Thanks for your PR! Apart from my comment https://github.com/zauberzeug/nicegui/pull/616#issuecomment-1482994695 regarding the PR itself, I have some thoughts about the big picture.

PR #616 will fix the interactive image. But it looks like this is only the tip of the iceberg. Here is a quick demo with all custom components. Most of them are not correctly replaced.

```py
import plotly.graph_objects as go
from nicegui import ui

with ui.card(), ui.row() as container:
    ui.log().push('A')
    ui.markdown('A')
    ui.mermaid('graph LR; A;')
    ui.colors(primary='blue')
    ui.audio('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3')
    ui.video('https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4').classes('h-32')
    ui.interactive_image('https://picsum.photos/id/29/640/360').classes('h-32')
    ui.aggrid({'columnDefs': [{'field': 'name'}], 'rowData': [{'name': 'Alice'}]}).classes('w-32 h-32')
    ui.chart({'series': [{'name': 'A'}]}).classes('w-32 h-32')
    ui.plotly(go.Figure(go.Scatter(x=[1, 2], y=[1, 2]))).classes('w-64 h-64')
    with ui.scene(width=100, height=100) as scene:
        scene.sphere()

def update():
    container.clear()
    with container:
        ui.log().push('B')
        ui.markdown('B')
        ui.mermaid('graph LR; B;')
        ui.colors(primary='red')
        ui.audio('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3')
        ui.video('https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4').classes('h-32')
        ui.interactive_image('https://picsum.photos/id/30/640/360').classes('h-32')
        ui.aggrid({'columnDefs': [{'field': 'name'}], 'rowData': [{'name': 'Bob'}]}).classes('w-32 h-32')
        ui.chart({'series': [{'name': 'B'}]}).classes('w-32 h-32')
        ui.plotly(go.Figure(go.Scatter(x=[1, 2], y=[2, 1]))).classes('w-64 h-64')
        with ui.scene(width=100, height=100) as scene:
            scene.box()

ui.button('Update', on_click=update)

ui.run()
```

So I see the following options:

1. Fix all custom components as @dclause did for `ui.interactive_image`.

    This sounds appealing, but is the most challenging.
    And as soon as other contributors or NiceGUI users write new components, they might introduce the very same bug again.

2. Add a unique "key" to each custom element.

    This is pretty easy to implement (we already tested a proof-of-concept).
    But regarding future components, the pitfall remains.

3. Add a unique "key" to each and every NiceGUI element.

    This should be bullet-proof.
    The only downside might be that we disable "in-place patching" completely, which might have an impact on performance.

@dclause What do you think, is performance an issue here? Maybe it doesn't matter too much, considering the overall latency caused by client-server communication.

Personally, I'd love to see further improvement to our JS code (option 1). Besides that, fixing this issue once and for all would be nice, too (option 3).

**Comment by falkoschindler** [comment]
@dclause Ok, sounds reasonable. 👍

Just for clarification: I wouldn't prevent in-place patching for every value change. I would set a prop "key" to the element's ID (which remains constant until the element is removed). More precisely: replace https://github.com/zauberzeug/nicegui/blob/9f955f90c5c5a903894c27e60a8bd5cda46634f2/nicegui/element.py#L40 with `self._props: Dict[str, Any] = {self.id}`. The bug is gone and Vue _should_ be able to re-use DOM elements as long as the corresponding NiceGUI element lives.

Regarding defective elements: At a first glance `ui.colors` and `ui.log` are buggy as well. But I'll try to write an automated test and check every component once again more systematically.

And yes, `ui.scene` is a beast. But if need be we can leave it unchanged for now. It seems a rare edge case to replace a 3D scene instantly. Or we use the "key" hack for this element only.

**Comment by dclause** [comment]
@falkoschindler Have you tried your suggestion ? I don't understand how this differs from the already existing `id: element.id,` which is in index.html and that already add an id prop to every component in the DOM. 
Do I miss something ? Does that works ?
I mean, that still does not make the "template" key differ. We are mixin the JSX and vue syntax here, this is an advanced use case I am not sure how vue is supposed to react on this.

**Comment by falkoschindler** [comment]
@dclause Yes, @rodja and I tried it yesterday and it worked. Nevertheless, I should check once again. Who knows if we mixed something up. But for now, I'll call it a day.

**Comment by falkoschindler** [comment]
Yes, `self._props: Dict[str, Any] = {'key': self.id}` fixes almost all element from [my previous comment](https://github.com/zauberzeug/nicegui/issues/600#issuecomment-1483067509). Only the `ui.log` contains two "B"s instead of one.

**Comment by DavidLeBonk** [comment]
Then ended up being a wayy bigger bug then I thought

**Comment by rodja** [comment]
What are the remaining todos for this issue?

**Comment by falkoschindler** [comment]
@rodja There's a task list at the top and I'm in charge.

**Comment by falkoschindler** [comment]
Ok, I added pytests for all custom elements.
For the failing elements `aggrid`, `chart`, `colors`, `log`, and `scene` I added a workaround in form of a unique key prop. From my point of view we can close this issue as completed. Or do we want to keep it open to track the actual fix of those elements, once we find out how?
