### ISSUE TITLE
Script seems to run method that isn't called

### ISSUE THREAD

**Issue by 2000Nic** [zauberzeug/nicegui#648]
The function remove_param() seems to be called when running the ui. The QDA_setup class is called in main.py. Upon loading in the browser both "render" and "remove" are printed to the console indicating that the remove_param() function has been triggered, however it is only referenced in the on_click of a button.

```py
from nicegui import ui

class QDA_setup:
    params = [{"low": "Ikke sur", "name": "Surhed", "high": "Meget sur"}]

    def __init__(self):
        ui.label("Upload konfigurationsfil:").classes("text-h5 text-primary")
        ui.upload(label="Vælg fil").props("accept=.json multiple=false no-thumbnails=true ")
        self.render_params()
        ui.button("Tilføj parameter")

    def render_params(self):
        container = ui.element('div')
        container.clear()
        print("render")
        with container:
            for i in range(len(self.params)):
                with ui.element('div').classes("items-center justify-between").style("width: 70vw; display: inline-flex"):
                    param = self.params[i]
                    ui.input('Laveste værdi', value=param['low']).style("width: 25%")
                    ui.input('Parameternavn', value=param['name']).style("width: 25%")
                    ui.input('Højeste værdi', value=param['high']).style("width: 25%")
                    ui.button(on_click=self.remove_param(i)).props("icon=highlight_off flat color=primary")

    def remove_param(self, i):
        del self.params[i]
        print("remove")
```

**Comment by 2000Nic** [comment]
I forgot to mention that the on_click itself doesn't seem to do anything

**Comment by HilkopterBob** [comment]
Hey, try writing your on_click call in a lambda function, ie.:
` ui.button(on_click=lambda: self.remove_param(i)).props("icon=highlight_off flat color=primary")`

**Comment by HilkopterBob** [comment]
thats a question for the @zauberzeug-dev 's

**Comment by falkoschindler** [comment]
@HilkopterBob

- When defining a button like `ui.button(on_click=do_something())`, the function `do_something` is _called_ at the moment when the button is defined. This is due to the parentheses, which invoke any callable object like a function. This is usually not what you want.
- When defining a button like `ui.button(on_click=do_something)`, the function `do_something` is passed as an argument to `ui.button`. It is _not_ called, because there are no parentheses.
- When defining a button like `ui.button(on_click=lambda: do_something())`, you're creating a new function in form of a lambda expression that is passed as an argument. When calling the lambda function (on a click event), the lambda expression is evaluated, which calls `do_something` because there are trailing parentheses.

So whenever you can't just pass the function directly, wrap it in a lambda expression (or regular function). Otherwise, don't use parentheses.

**Comment by HilkopterBob** [comment]
@falkoschindler thats the longer and better version of what i all ready wrote, see:

> Hey, try writing your on_click call in a lambda function, ie.: ` ui.button(on_click=lambda: self.remove_param(i)).props("icon=highlight_off flat color=primary")`

**Comment by falkoschindler** [comment]
@HilkopterBob Sure. I tried to also answer "Shouldn't the other option work too though" you've been forwarding to the Zauberzeug developers (which includes me). 😉

**Comment by 2000Nic** [comment]
Thanks for the clarification @falkoschindler
