### ISSUE TITLE
ui.upload rejected events not fired when filesize bigger than ~972kb

### ISSUE THREAD

**Issue by gitUser000** [zauberzeug/nicegui#685]
### Description

Hi, 

I notice a strange behavior with the ui.upload element (v1.2.2) when you set a file size limit (here 100kb but same happens if set to 1kb, it doesn't seem to have any impact)

- if I upload a 972kb (or less) file : I do get the max size exceeded alert.
- if I upload a 978kb file : file is not loaded BUT nothing happens (no alert displayed)

I didn't find out from which specific file size the change occurs

Here is the code used to test

```python
from nicegui import ui

@ui.page('/')
async def main_page():
    # Upload file : cf. https://quasar.dev/vue-components/uploader
    g_file_upload = \
        ui.upload(label="Select or drop a file here(100kb Max)", auto_upload=True, on_upload= lambda: ui.notify('upload'))\
        .props(' color="amber" text-color="black" max-file-size="102400" ')\
        .on('rejected', lambda: ui.notify('max file size limited to 100kb'))\
        .classes('w-auto')

ui.run(title='Loader Test', port=8080, show=False, reload = True)

```
Note that I do not observe this behavior if I test the same files on the following page (Quasar Framework):
https://quasar.dev/vue-components/uploader#restricting-upload (2k max file size)

(Not tested with last 1.2.3 version, tested with several filetype : test, pdf, png, binary, ...)

**Comment by falkoschindler** [comment]
Very interesting bug... Thanks for reporting, @gitUser000!

We can reproduce it with the following line. When uploading a file with a size of several MB, no notification is shown:
```py
ui.upload().props('max-file-size=102400').on('rejected', lambda: ui.notify('rejected'))
```

I guess what's happening is the following: As part of the "rejected" event the client wants to send an array of `rejectedEntries`, which consist of `{ failedPropValidation: string, file: File }` (see [QUploader documentation](https://quasar.dev/vue-components/uploader)). In our context it is pretty pointless to send a file that violates a size limit. And since the file is sent via websockets, we quickly run into serious trouble (probably at around 1MB) and the client seems to disconnect.

A workaround is to explicitly request _no_ event arguments:
```py
ui.upload().props('max-file-size=102400').on('rejected', lambda: ui.notify('rejected'), args=[])
```

Over at https://github.com/zauberzeug/nicegui/issues/672 we're already thinking about the generic event API and how to make the argument list more transparent. Besides that, we should introduce an `on_rejected` parameter for `ui.upload` so that the user code doesn't have to deal with these details.
