### ISSUE TITLE
hotfix / workaround for #693

### ISSUE THREAD

**Issue by HilkopterBob** [zauberzeug/nicegui#699]
### Description

is there a hotfix/workaround for issue #693?

i know you guys fixed it and its part of V1.2.4 but besides that is there anything i can do to allow redirects from my async pages?

**Comment by rodja** [comment]
You could probably copy the fixed page decorator into your own code and use it instead of `@ui.page`. Or you check out NiceGUI main branch and install it with `python3 -m pip install -e` (see https://github.com/zauberzeug/nicegui/blob/main/CONTRIBUTING.md#setup) to make the fixed package available in your system.

We plan on releasing 1.2.4 tomorrow (not 24 hours from now).

**Comment by HilkopterBob** [comment]
thanks for the info @rodja 👍🏻
