### ISSUE TITLE
cannot run with pythonw.exe

### ISSUE THREAD

**Issue by thienphuoc86** [zauberzeug/nicegui#719]
### Description

nicegui script cannot run with pythonw.exe

**Comment by falkoschindler** [comment]
Thank you for reaching out! In order to assist you more effectively, we need some additional information about your issue. Please provide the following details:

- A brief description of the problem you're facing or the objective you're trying to achieve.
- A [minimal, complete, and verifiable example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) of the code you're using. This will help us understand the context and reproduce the issue on our end.
- The exact error message or unexpected behavior you're encountering when you attempt to run the script with pythonw.exe. If applicable, please include any relevant screenshots or logs.

By providing this information, we'll be better equipped to diagnose the issue and offer a targeted solution. We appreciate your cooperation and look forward to helping you resolve this problem.

**Comment by thienphuoc86** [comment]
I tried with demo code

test.py
```
from nicegui import app,ui

class Demo:
    def __init__(self):
        self.number = 1

demo = Demo()
v = ui.checkbox('visible', value=True)
with ui.column().bind_visibility_from(v, 'value'):
    ui.slider(min=1, max=3).bind_value(demo, 'number')
    ui.toggle({1: 'A', 2: 'B', 3: 'C'}).bind_value(demo, 'number')
    ui.number().bind_value(demo, 'number')

app.native.window_args['resizable'] = False
ui.run(native=True, window_size=(400, 400), fullscreen=False)
```

After that run it with command C:/Python310/pythonw.exe test.py
The result is as snapshot below. 
![image](https://user-images.githubusercontent.com/86188301/229850513-03061b11-4e88-498c-aeae-dfd927b0885b.png)

**Comment by falkoschindler** [comment]
@thienphuoc86 And you still get "Hmmm... can't reach this page"?

**Comment by falkoschindler** [comment]
@thienphuoc86 Maybe you can try the following code. It also writes the error output to a file "myerr.txt".

```py
import sys
from nicegui import ui

sys.stdout = open("mylog.txt", "w")
sys.stderr = open("myerr.txt", "w")

ui.label('Hello, world!')
ui.run(native=True)
```

**Comment by thienphuoc86** [comment]
Hi Falko Schindler,
I tried your code but the same result.
Nothing in mylog.txt and myerror.txt
And still get the "Hmmm... can't reach this page"
![image](https://user-images.githubusercontent.com/86188301/231806491-1bbebebd-a196-42ac-85e3-c09d0c0024c4.png)

**Comment by thienphuoc86** [comment]
Hi Falko Schindler,
I tried but the same result. Thank you very much for your support!

**Comment by falkoschindler** [comment]
I'm pretty much out of ideas. Has anyone else more experience with pythonw?

**Comment by edsase** [comment]
Hi, please try the following code in your `test6.py`:
```
from nicegui import ui

import sys, os

sys.stdout = open(os.devnull, 'w') # redirect to devnull, works on windows too
ui.label('Hello NiceGUI!')
ui.button('BUTTON', on_click=lambda: ui.notify('button was pressed'))
ui.run(native=True, reload=False)
```
Note that as given above, you should use the `reload=False` flag when calling `ui.run` with `native=True`.

**Comment by thienphuoc86** [comment]
Thanks Edmond Sesay;
I followed your instruction and now it can run with pythonw.exe :)
