### ISSUE TITLE
NiceGUI runs python code twice

### ISSUE THREAD

**Issue by JS-Aibel** [zauberzeug/nicegui#794]
### Description

When running the code below the python code get executed twice.
When running scripts that takes a while, it is bad for performance that it has to run twice.

```py
from nicegui import ui

print("Start")
print("End")

ui.label("test")
ui.run()
```

**Output from terminal:**
```
> python test.py
Start
End
Start
End
NiceGUI ready to go on http://0.0.0.0:8080
```

**Comment by falkoschindler** [comment]
Thanks for bringing this up, @JS-Aibel!

This is known behavior. When running with `ui.run(reload=True)` (the default) there are two processes:
- The main process evaluates the script, runs `ui.run` and starts the uvicorn server.
- Because `reload=True`, it starts another process that also evaluates the script. Whenever the code is changed, this child process is replaced with a new one that evaluates the script again.

Note that the script is evaluated twice only when starting it. The auto-reload on code change will re-evaluate only once.

To avoid the re-evaluation, you have several options:

- Use `ui.run(reload=False)`. Of course, you loose the handy auto-reload feature. But for production this might be the way to go.

- Use some kind of main guard:
    ```py
    from nicegui import ui

    if __name__ == '__mp_main__':
        print("Start")
        print("End")
        ui.label("test")

    ui.run()
    ```
    This avoids evaluating the code in the `"__main__"` process and restricts it to the child process `"__mp_main__"`.

- Use a page decorator:
    ```py
    @ui.page('/')
    def main():
        print("Start")
        print("End")
        ui.label("test")
    ```
    This evaluates the UI only when accessed. But if you have an expensive initialization to do once when starting the script, this might not be the way to go. Page decorators also change the visibility, since it generates a new page per client, so the state is not shared anymore.

- Move expensive initialization into a startup callback:
    ```py
    def startup():
        print("Start")
        print("End")
    
    app.on_startup(startup)
    
    ui.label("test")
    ```
    This way `startup` is only evaluated once in the child process, since the app doesn't _start_ in the main process (unless `reload=False`).

**Comment by itd-fsc** [comment]
We solved this by creating an empty UI if reload is enabled and if it is the process that will just start the script again
```python
RELOAD = True


def main():
    # If reload is enabled, then it has to run the main program as a subprocess (https://github.com/zauberzeug/nicegui/issues/794)
    # => it runs the file again as a subprocess causing everything to be executed twice
    # => This reload runner doesn't need to run the actual code
    if RELOAD and __name__ == '__main__':
        ui.run(host='127.0.0.1', port=8080, reload=RELOAD)
        return
    
    print("Building UI")
    ui.label('Test')
    ui.run(host='127.0.0.1', port=8080, reload=RELOAD)


if __name__ in ['__main__', '__mp_main__']:
    main()

```
