### ISSUE TITLE
NiceGUI ignores FastAPI/uvicorn root_path parameter

### ISSUE THREAD

**Issue by wdroz** [zauberzeug/nicegui#848]
### Description

Hi,

I use NiceGUI with an existing FastAPI. The web application is hosted behind an reverse proxy with a **prefix** in the URL. But whatever I use 

```python
FastAPI(root_path=path_prefix)
```

or

```bash
uvicorn --root-path MY_ROOT_PATH ...
```

NiceGUI is ignoring that parameter and try to fetch resources to `BASE_URL/_nicegui/` instead of `BASE_URL/PATH_PREFIX/_nicegui/`

The `BASE_URL/PATH_PREFIX/docs` works as intended and is able to fetch `BASE_URL/PATH_PREFIX/openapi.json`

I would like to avoid to use the workaround [Serving an App Behind a Reverse Proxy Subpath](https://github.com/zauberzeug/nicegui/tree/main/examples/nginx_subpath) that fiddle with the proxy.

**Comment by rodja** [comment]
Thanks for pointing this out @wdroz. I had the assumption that the path_prefix is a bit unpopular because of it's inflexibility. But that may only be caused by our own mobile-robot centric requirements (serving the same content over local wifi and also via vpn tunnel and reverse proxy).

We may just need to [check the current root path](https://fastapi.tiangolo.com/advanced/behind-a-proxy/#checking-the-current-root_path) and insert it as prefix in the client if no `X-Forwarded-Prefix` header is set: https://github.com/zauberzeug/nicegui/blob/8a86d2064f8f4464f3819ac5c6763a2cb2d0e990/nicegui/client.py#L71

**Comment by rodja** [comment]
Maybe someone wants to take this to a pull request?
