### ISSUE TITLE
Untyped decorator for ui.page()

### ISSUE THREAD

**Issue by AndrewMHenry** [zauberzeug/nicegui#949]
# Summary

In our NiceGUI project, mypy gives an untyped function error in strict mode when using the `ui.page()` decorator.

# MWE

The following example (in file `mwe.py`) creates a simple app with a single main page:
```python
from nicegui import ui


@ui.page("/")
def main_page() -> None:
    ui.label("Hello World!")


ui.run()
```

# Expected behavior

There should not be any mypy type errors.

# Actual behavior

Running `mypy --strict mwe.py` produces the following error:
```
mwe.py:4: error: Untyped decorator makes function "main_page" untyped  [misc]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by falkoschindler** [comment]
Thanks for reporting this issue, @AndrewMHenry!
This specific error should be fixed with [e3e42ee](https://github.com/zauberzeug/nicegui/commit/e3e42eef5f726bf4893daa8abd06d259f0a42cfd). But better mypy and pyright support is still an open topic (see https://github.com/zauberzeug/nicegui/discussions/762). Pull requests to further improve type annotations are always welcome.
